GRPD::Material::MaterialManager Class Reference
#include <MaterialManager.h>
Public Member Functions
MaterialManager ()=default
~MaterialManager ()=default
MaterialManager (const MaterialManager &)=delete
MaterialManager & operator= (const MaterialManager &)=delete
MaterialManager (MaterialManager &&)=default
MaterialManager & operator= (MaterialManager &&)=default
void addMaterial (const std::string &name, std::unique_ptr< Material > material)
添加一个已创建好的材料实例到当前管理器中
Material * getMaterial (const std::string &name)
获取已实例化的材料对象指针
const Material * getMaterial (const std::string &name) const
bool hasMaterial (const std::string &name) const
检查材料实例是否存在
size_t getMaterialCount () const
获取已注册材料总数
const std::map< std::string, std::unique_ptr< Material > > & getMaterials () const
获取所有材料的引用（用于遍历，如分配状态变量）
Private Attributes
std::map< std::string, std::unique_ptr< Material > > materials_
Detailed Description
Definition at line 17 of file MaterialManager.h.
Constructor & Destructor Documentation
MaterialManager() [1/3]
GRPD::Material::MaterialManager::MaterialManager () [default]
Referenced by MaterialManager(), MaterialManager(), operator=(), and operator=().
~MaterialManager()
GRPD::Material::MaterialManager::~MaterialManager () [default]
MaterialManager() [2/3]
GRPD::Material::MaterialManager::MaterialManager (const MaterialManager &) [delete]
References MaterialManager().
MaterialManager() [3/3]
GRPD::Material::MaterialManager::MaterialManager (MaterialManager &&) [default]
References MaterialManager().
Member Function Documentation
addMaterial()
void GRPD::Material::MaterialManager::addMaterial (const std::string & name, std::unique_ptr< Material > material)
添加一个已创建好的材料实例到当前管理器中
Parameters
name 材料实例名称（如 "Steel", "Aluminum"）
material 材料实例的所有权（unique_ptr）
Definition at line 14 of file MaterialManager.cpp.
                                                                    {
  if (materials_.find(name) != materials_.end()) {
    LOG_WARNING("[MaterialManager] Material '" + name +
                "' has been exist, overwriting.");
  }
  materials_[name] = std::move(material);
  LOG_INFO("[MaterialManager] Successfully added material instance: " + name);
}
References LOG_INFO, LOG_WARNING, and materials_.
getMaterial() [1/2]
Material * GRPD::Material::MaterialManager::getMaterial (const std::string & name)
获取已实例化的材料对象指针
Parameters
name 材料实例名称
Definition at line 27 of file MaterialManager.cpp.
                                                            {
  auto it = materials_.find(name);
  if (it == materials_.end()) {
    LOG_ERROR("[MaterialManager] Failed to find material instance: " + name);
    throw std::runtime_error("Not find material instance" + name);
  }
  return it->second.get();
}
References LOG_ERROR, and materials_.
getMaterial() [2/2]
const Material * GRPD::Material::MaterialManager::getMaterial (const std::string & name) const
Definition at line 36 of file MaterialManager.cpp.
                                                                        {
  auto it = materials_.find(name);
  if (it == materials_.end()) {
    LOG_ERROR("[MaterialManager] Failed to find material instance: " + name);
    throw std::runtime_error("Not find material instance: " + name);
  }
  return it->second.get();
}
References LOG_ERROR, and materials_.
getMaterialCount()
size_t GRPD::Material::MaterialManager::getMaterialCount () const [inline]
获取已注册材料总数
Definition at line 48 of file MaterialManager.h.
{ return materials_.size(); }
References materials_.
getMaterials()
const std::map< std::string, std::unique_ptr< Material > > & GRPD::Material::MaterialManager::getMaterials () const [inline]
获取所有材料的引用（用于遍历，如分配状态变量）
Definition at line 51 of file MaterialManager.h.
                                                                         {
    return materials_;
  }
References materials_.
hasMaterial()
bool GRPD::Material::MaterialManager::hasMaterial (const std::string & name) const
检查材料实例是否存在
Definition at line 48 of file MaterialManager.cpp.
                                                             {
  return materials_.find(name) != materials_.end();
}
References materials_.
operator=() [1/2]
MaterialManager & GRPD::Material::MaterialManager::operator= (const MaterialManager &) [delete]
References MaterialManager().
operator=() [2/2]
MaterialManager & GRPD::Material::MaterialManager::operator= (MaterialManager &&) [default]
References MaterialManager().
Member Data Documentation
materials_
std::map<std::string, std::unique_ptr<Material> > GRPD::Material::MaterialManager::materials_ [private]
Definition at line 57 of file MaterialManager.h.
Referenced by addMaterial(), getMaterial(), getMaterial(), getMaterialCount(), getMaterials(), and hasMaterial().
The documentation for this class was generated from the following files:
PDCommon/Material/include/MaterialManager.h
PDCommon/Material/src/MaterialManager.cpp