GRPD::IO::GrpdReader Class Reference
#include <GrpdReader.h>
Static Public Member Functions
static bool read (const std::string &filepath, GRPD::Model::ParticleManager &manager)
static bool readLoads (const std::string &filepath, GRPD::Core::PDSimulater &simulater)
Private Types
enum class ParseState { IDLE
, READING_PARTICLES
, READING_LOADS
 }
内部解析状态枚举
using LineCallback
Static Private Member Functions
static bool scanFile (const std::string &filepath, LineCallback callback, const std::string &logPrefix)
static std::vector< std::string > tokenizeCsv (const std::string &line)
将逗号分隔的一行文本分割为修剪后的字段数组
static std::string trim (const std::string &s)
去除字符串首尾空白字符
Detailed Description
Definition at line 27 of file GrpdReader.h.
Member Typedef Documentation
LineCallback
using GRPD::IO::GrpdReader::LineCallback [private]
Initial value:
 std::function<bool(ParseState state,
                                          const std::vector<std::string> &tokens,
                                          int lineNumber)>
Definition at line 59 of file GrpdReader.h.
Member Enumeration Documentation
ParseState
enum class GRPD::IO::GrpdReader::ParseState [strong], [private]
内部解析状态枚举
Enumerator
IDLE
READING_PARTICLES
READING_LOADS
Definition at line 49 of file GrpdReader.h.
                        {
    IDLE, // 初始状态，等待段标记
    READING_PARTICLES, // 正在读取 *PARTICLE 段
    READING_LOADS // 正在读取 *LOAD 段
  };
Member Function Documentation
read()
bool GRPD::IO::GrpdReader::read (const std::string & filepath, GRPD::Model::ParticleManager & manager) [static]
Definition at line 119 of file GrpdReader.cpp.
                                                         {
  int particleCount = 0;
  int loadCount = 0;
  bool ok = scanFile(
      filepath,
      [&](ParseState state, const std::vector<std::string> &tokens,
          int lineNumber) -> bool {
        // ===== *PARTICLE 段：解析 ID, PartID, MatID, X, Y, Z, Volume =====
        if (state == ParseState::READING_PARTICLES) {
          if (tokens.size() != 7) {
            LOG_WARNING(
                "[GrpdReader] Line " + std::to_string(lineNumber) +
                " particle field count=" + std::to_string(tokens.size()) +
                ", expected 7, skipped");
            return true; // 跳过当前行，继续扫描
          }
          try {
            int id = std::stoi(tokens[0]);
            int partId = std::stoi(tokens[1]);
            int matId = std::stoi(tokens[2]);
            double x = std::stod(tokens[3]);
            double y = std::stod(tokens[4]);
            double z = std::stod(tokens[5]);
            double vol = std::stod(tokens[6]);
            manager.addParticle(id, partId, matId, x, y, z, vol);
            particleCount++;
          } catch (const std::exception &e) {
            LOG_ERROR("[GrpdReader] Line " + std::to_string(lineNumber) +
                      " parse failed: " + std::string(e.what()));
          }
        }
        // ===== *LOAD 段：仅计数，实际处理由 readLoads() 负责 =====
        if (state == ParseState::READING_LOADS) {
          loadCount++;
        }
        return true; // 继续扫描
      },
      "GrpdReader");
  if (!ok)
    return false;
  // 打印汇总统计
  LOG_INFO("[GrpdReader] ============================================");
  LOG_INFO("[GrpdReader] File reading complete!");
  LOG_INFO("[GrpdReader] Total particles: " + std::to_string(particleCount));
  LOG_INFO("[GrpdReader] Total load entries: " + std::to_string(loadCount));
  LOG_INFO("[GrpdReader] ============================================");
  return true;
}
References GRPD::Model::ParticleManager::addParticle(), LOG_ERROR, LOG_INFO, LOG_WARNING, READING_LOADS, READING_PARTICLES, and scanFile().
Referenced by GRPD::Engine::SolverEngine::InitModelPD().
readLoads()
bool GRPD::IO::GrpdReader::readLoads (const std::string & filepath, GRPD::Core::PDSimulater & simulater) [static]
Definition at line 181 of file GrpdReader.cpp.
                                                           {
  auto &fieldManager = simulater.getFieldManager();
  auto &bcManager = simulater.getBCManager();
  // 检查温度场是否已注册
  if (!fieldManager.hasField("Temperature")) {
    LOG_WARNING("[GrpdReader] Temperature field not registered. Skipping loads.");
    return false;
  }
  // 获取温度场指针（用于 Dirichlet 初始值设置）
  auto *tempField = fieldManager.getFieldAs<double>("Temperature");
  int tempCount = 0;
  int fluxCount = 0;
  int convCount = 0;
  int otherCount = 0;
  bool ok = scanFile(
      filepath,
      [&](ParseState state, const std::vector<std::string> &tokens,
          int lineNumber) -> bool {
        if (state != ParseState::READING_LOADS)
          return true;
        if (tokens.size() < 4)
          return true;
        try {
          int id = std::stoi(tokens[0]);
          int bcId = std::stoi(tokens[1]);
          std::string type = tokens[2];
          std::vector<double> values;
          for (size_t i = 3; i < tokens.size(); i++) {
            values.push_back(std::stod(tokens[i]));
          }
          // 使用 BcID 作为 BC 名称前缀，实现分类标记
          std::string bcName =
              type + "_BC" + std::to_string(bcId) + "_P" + std::to_string(id);
          // 通过 BCRegistry 工厂创建 BC 实例（消除 if/else）
          auto bc = GRPD::BC::BCRegistry::getInstance().createBC(type, bcName);
          if (!bc) {
            LOG_WARNING("[GrpdReader] Unknown BC type: " + type);
            otherCount++;
          } else {
            bc->initialize(fieldManager, id, values);
            // Dirichlet 约束需要同步设置初始温度值
            if (bc->isConstraint()) {
              tempField->set(id, values[0]);
              tempCount++;
            } else if (type == "FLUX") {
              auto *heatFluxField = fieldManager.getFieldAs<double>("HeatFlux");
              if (heatFluxField) {
                heatFluxField->set(id, values[0]);
              }
              fluxCount++;
            } else {
              convCount++;
            }
            bcManager.addBC(std::move(bc));
          }
        } catch (const std::exception &e) {
          LOG_ERROR("[GrpdReader::readLoads] Line " +
                    std::to_string(lineNumber) +
                    " parse failed: " + std::string(e.what()));
        }
        return true;
      },
      "GrpdReader::readLoads");
  if (!ok)
    return false;
  LOG_INFO("[GrpdReader::readLoads] Load statistics:");
  LOG_INFO(" - Temperature (Dirichlet): " + std::to_string(tempCount));
  LOG_INFO(" - Heat Flux (Neumann): " + std::to_string(fluxCount));
  LOG_INFO(" - Convection (Robin): " + std::to_string(convCount));
  if (otherCount > 0)
    LOG_WARNING(" - Unknown types: " + std::to_string(otherCount));
  return true;
}
References GRPD::BC::BCRegistry::createBC(), GRPD::Core::PDSimulater::getBCManager(), GRPD::Core::PDSimulater::getFieldManager(), GRPD::BC::BCRegistry::getInstance(), LOG_ERROR, LOG_INFO, LOG_WARNING, READING_LOADS, and scanFile().
Referenced by GRPD::Engine::SolverEngine::InitConditionsPD().
scanFile()
bool GRPD::IO::GrpdReader::scanFile (const std::string & filepath, LineCallback callback, const std::string & logPrefix) [static], [private]
Definition at line 52 of file GrpdReader.cpp.
                                                      {
  // 1. 打开文件
  std::ifstream file(filepath);
  if (!file.is_open()) {
    LOG_ERROR("[" + logPrefix + "] Error: cannot open file \"" + filepath +
              "\"");
    return false;
  }
  // 2. 状态机初始化
  ParseState state = ParseState::IDLE;
  std::string line;
  int lineNumber = 0;
  // 3. 逐行扫描
  while (std::getline(file, line)) {
    lineNumber++;
    // 去除首尾空白
    std::string trimmedLine = trim(line);
    // 跳过空行
    if (trimmedLine.empty()) {
      continue;
    }
    // 跳过注释行（以 # 开头）
    if (trimmedLine[0] == '#') {
      continue;
    }
    // ----- 段标记检测：切换状态 -----
    if (trimmedLine == "*PARTICLE") {
      state = ParseState::READING_PARTICLES;
      LOG_INFO("[" + logPrefix + "] Entering *PARTICLE section (Line " +
               std::to_string(lineNumber) + ")");
      continue;
    }
    if (trimmedLine == "*LOAD") {
      state = ParseState::READING_LOADS;
      LOG_INFO("[" + logPrefix + "] Entering *LOAD section (Line " +
               std::to_string(lineNumber) + ")");
      continue;
    }
    // IDLE 状态下忽略数据行
    if (state == ParseState::IDLE) {
      continue;
    }
    // ----- 分割字段并调用回调 -----
    auto tokens = tokenizeCsv(line);
    if (!callback(state, tokens, lineNumber)) {
      break; // 回调返回 false 则终止扫描
    }
  }
  file.close();
  return true;
}
References IDLE, LOG_ERROR, LOG_INFO, READING_LOADS, READING_PARTICLES, tokenizeCsv(), and trim().
Referenced by read(), and readLoads().
tokenizeCsv()
std::vector< std::string > GRPD::IO::GrpdReader::tokenizeCsv (const std::string & line) [static], [private]
将逗号分隔的一行文本分割为修剪后的字段数组
Definition at line 37 of file GrpdReader.cpp.
                                                                  {
  std::vector<std::string> tokens;
  std::istringstream ss(line);
  std::string token;
  while (std::getline(ss, token, ',')) {
    tokens.push_back(trim(token));
  }
  return tokens;
}
References trim().
Referenced by scanFile().
trim()
std::string GRPD::IO::GrpdReader::trim (const std::string & s) [static], [private]
去除字符串首尾空白字符
Definition at line 26 of file GrpdReader.cpp.
                                             {
  auto start = s.find_first_not_of(" \t\r\n");
  if (start == std::string::npos)
    return "";
  auto end = s.find_last_not_of(" \t\r\n");
  return s.substr(start, end - start + 1);
}
Referenced by scanFile(), and tokenizeCsv().
The documentation for this class was generated from the following files:
PDCommon/IO/include/GrpdReader.h
PDCommon/IO/src/GrpdReader.cpp