GRPD::IO::VtkWriter Class Reference
#include <VtkWriter.h>
Public Member Functions
VtkWriter ()
VtkWriter (std::string filename, int nP, fileFormat f)
~VtkWriter () override
void write () override
bool setPointsNumber (int nP) override
Public Member Functions inherited from GRPD::IO::Writer
Writer ()
Writer (std::string filename, int nP, fileFormat f)
virtual ~Writer ()
void open (std::string filename, fileFormat f)
int getPointsNumber ()
void setFormat (fileFormat f)
fileFormat getFormat ()
void setPointsInfo (dataType type, void *ptr, std::string name="Points", int width=3)
void setPointsVariable (dataType type, void *ptr, std::string name, int width)
Private Member Functions
void writePoints ()
void writeCells ()
void writeCellTypes ()
void writePointsVariable ()
template<typename T>
void writeAscii (T *arr, int width)
template<typename T>
void writeBinary (T *arr, int width)
template<typename T>
void writeArrayBinary (T *arr, int width)
void convertEndian (char *buf, void *ptr, dataType type, int length)
Private Attributes
dataInfoStruct cells
dataInfoStruct cellTypes
char * buf
Additional Inherited Members
Protected Attributes inherited from GRPD::IO::Writer
std::ofstream outFile
int pointsNumber
fileFormat format
dataInfoStruct pointsInfo
std::vector< dataInfoStruct > pointsVariable
Detailed Description
Definition at line 8 of file VtkWriter.h.
Constructor & Destructor Documentation
VtkWriter() [1/2]
GRPD::IO::VtkWriter::VtkWriter ()
Definition at line 8 of file VtkWriter.cpp.
                     : Writer() {
  cells.ptr = nullptr;
  cells.name = "CELLS";
  cells.type = Int32;
  cells.typeStr = "Int32";
  cells.width = 2; // 物质点是2，FEM网格可能是5或者9
  cellTypes.ptr = nullptr;
  cellTypes.name = "CELL_TYPES";
  cellTypes.type = Int32;
  cellTypes.typeStr = "Int32";
  cellTypes.width = 1;
  buf = nullptr;
}
References buf, cells, cellTypes, GRPD::IO::Int32, and GRPD::IO::Writer::Writer().
VtkWriter() [2/2]
GRPD::IO::VtkWriter::VtkWriter (std::string filename, int nP, fileFormat f)
Definition at line 24 of file VtkWriter.cpp.
    : Writer(filename, nP, f) {
  cells.ptr = nullptr;
  cells.name = "CELLS";
  cells.type = Int32;
  cells.typeStr = "Int32";
  cells.width = 2; // 物质点是2，FEM网格可能是5或者9
  cellTypes.ptr = nullptr;
  cellTypes.name = "CELL_TYPES";
  cellTypes.type = Int32;
  cellTypes.typeStr = "Int32";
  cellTypes.width = 1;
  setPointsNumber(nP);
}
References cells, cellTypes, GRPD::IO::Int32, setPointsNumber(), and GRPD::IO::Writer::Writer().
~VtkWriter()
GRPD::IO::VtkWriter::~VtkWriter () [override]
Definition at line 41 of file VtkWriter.cpp.
                      {
  if (pointsNumber > 0) {
    delete[] static_cast<int *>(cells.ptr);
    delete[] static_cast<int *>(cellTypes.ptr);
    delete[] buf;
  }
}
References buf, cells, cellTypes, and GRPD::IO::Writer::pointsNumber.
Member Function Documentation
convertEndian()
void GRPD::IO::VtkWriter::convertEndian (char * buf, void * ptr, dataType type, int length) [private]
Definition at line 291 of file VtkWriter.cpp.
                                                                             {
  char *cptr = static_cast<char *>(ptr);
  int width = 0;
  switch (type) {
  case Int32:
  case Float32:
    width = 4;
    break;
  case Int64:
  case Float64:
    width = 8;
    break;
  default:
    return;
  }
  for (int i = 0; i < length; i++) {
    char *src = cptr + i * width;
    char *dst = buf + i * width;
    for (int j = 0; j < width; j++) {
      dst[j] = src[width - 1 - j];
    }
  }
}
References buf, GRPD::IO::Float32, GRPD::IO::Float64, GRPD::IO::Int32, and GRPD::IO::Int64.
Referenced by writeCells(), writeCellTypes(), writePoints(), and writePointsVariable().
setPointsNumber()
bool GRPD::IO::VtkWriter::setPointsNumber (int nP) [override], [virtual]
Implements GRPD::IO::Writer.
Definition at line 49 of file VtkWriter.cpp.
                                      {
  try {
    if (nP < 0) {
      std::cout << "VtkWriter::setPointsNumber Failed: The number of points "
                   "must greater than zero!"
                << std::endl;
      throw std::runtime_error("");
    }
    if (nP == pointsNumber) {
      return true;
    } else {
      if (pointsNumber == -1) {
        pointsNumber = nP;
        cells.ptr = new int[nP * 2];
        cells.name = "CELLS";
        cells.type = Int32;
        cells.typeStr = "Int32";
        cells.width = 2; // 物质点是2，FEM网格可能是5或者9
        cellTypes.ptr = new int[nP];
        cellTypes.name = "CELL_TYPES";
        cellTypes.type = Int32;
        cellTypes.typeStr = "Int32";
        cellTypes.width = 1;
        buf = new char[nP * 9 * 8];
      } else {
        delete[] static_cast<int *>(cells.ptr);
        delete[] static_cast<int *>(cellTypes.ptr);
        delete[] buf;
        pointsNumber = nP;
        cells.ptr = new int[nP * 2];
        cellTypes.ptr = new int[nP];
        buf = new char[nP * 9 * 8];
      }
      int *cellsPTR = static_cast<int *>(cells.ptr);
      int *cellTypesPTR = static_cast<int *>(cellTypes.ptr);
      for (int i = 0; i < nP; i++) {
        int idx = 2 * i;
        cellsPTR[idx] = 1;
        cellsPTR[idx + 1] = i;
        cellTypesPTR[i] = 1;
      }
      return true;
    }
  } catch (const std::exception &e) {
    std::cerr << "Error:" << e.what();
    return false;
  }
}
References buf, cells, cellTypes, GRPD::IO::Int32, and GRPD::IO::Writer::pointsNumber.
Referenced by VtkWriter().
write()
void GRPD::IO::VtkWriter::write () [override], [virtual]
Implements GRPD::IO::Writer.
Definition at line 103 of file VtkWriter.cpp.
                      {
  outFile << "# vtk DataFile Version 4.2";
  outFile << '\n';
  outFile << "vtk output";
  outFile << '\n';
  std::string Format;
  switch (format) {
  case ascii:
    Format = "ASCII";
    break;
  case binary:
    Format = "BINARY";
    break;
  }
  outFile << Format << std::endl;
  outFile << "DATASET UNSTRUCTURED_GRID";
  outFile << '\n';
  writePoints();
  writeCells();
  writeCellTypes();
  writePointsVariable();
}
References GRPD::IO::ascii, GRPD::IO::binary, GRPD::IO::Writer::format, GRPD::IO::Writer::outFile, writeCells(), writeCellTypes(), writePoints(), and writePointsVariable().
Referenced by GRPD::Engine::SolverEngine::OutputPD().
writeArrayBinary()
template<typename T>
void GRPD::IO::VtkWriter::writeArrayBinary (T * arr, int width) [private]
References buf.
writeAscii()
template<typename T>
void GRPD::IO::VtkWriter::writeAscii (T * arr, int width) [private]
Definition at line 260 of file VtkWriter.cpp.
                                                                  {
  std::ios_base::fmtflags originalFlags = outFile.flags();
  std::streamsize originalPrecision = outFile.precision();
  outFile << std::scientific;
  outFile << std::setprecision(8);
  for (int i = 0; i < pointsNumber; ++i) {
    auto *rowStart = arr + i * width;
    for (int j = 0; j < width; j++) {
      T value = rowStart[j];
      outFile << std::setw(16) << value;
      if (j < width - 1) {
        outFile << " ";
      }
    }
    outFile << '\n';
  }
  outFile.flags(originalFlags);
  outFile.precision(originalPrecision);
}
References GRPD::IO::Writer::outFile, and GRPD::IO::Writer::pointsNumber.
Referenced by writeCells(), writeCellTypes(), writePoints(), and writePointsVariable().
writeBinary()
template<typename T>
void GRPD::IO::VtkWriter::writeBinary (T * arr, int width) [private]
Definition at line 280 of file VtkWriter.cpp.
                                                                   {
  try {
    size_t sz = static_cast<unsigned long>(pointsNumber * width) * sizeof(T);
    if (!outFile.write(reinterpret_cast<char *>(arr), static_cast<long>(sz))) {
      throw std::runtime_error("Failed to write data in binary form!");
    }
  } catch (const std::exception &e) {
    std::cerr << "Error:" << e.what();
  }
}
References GRPD::IO::Writer::outFile, and GRPD::IO::Writer::pointsNumber.
Referenced by writeCells(), writeCellTypes(), writePoints(), and writePointsVariable().
writeCells()
void GRPD::IO::VtkWriter::writeCells () [private]
Definition at line 168 of file VtkWriter.cpp.
                           {
  outFile << "CELLS " << pointsNumber << " " << pointsNumber * 2;
  outFile << '\n';
  switch (format) {
  case ascii:
    writeAscii(static_cast<int *>(cells.ptr), cells.width);
    break;
  case binary:
    convertEndian(buf, cells.ptr, Int32, pointsNumber * cells.width);
    writeBinary(reinterpret_cast<int *>(buf), cells.width);
    break;
  }
}
References GRPD::IO::ascii, GRPD::IO::binary, buf, cells, convertEndian(), GRPD::IO::Writer::format, GRPD::IO::Int32, GRPD::IO::Writer::outFile, GRPD::IO::Writer::pointsNumber, writeAscii(), and writeBinary().
Referenced by write().
writeCellTypes()
void GRPD::IO::VtkWriter::writeCellTypes () [private]
Definition at line 182 of file VtkWriter.cpp.
                               {
  outFile << "CELL_TYPES " << pointsNumber;
  outFile << '\n';
  switch (format) {
  case ascii:
    writeAscii(static_cast<int *>(cellTypes.ptr), cellTypes.width);
    break;
  case binary:
    convertEndian(buf, cellTypes.ptr, Int32, pointsNumber * cellTypes.width);
    writeBinary(reinterpret_cast<int *>(buf), cellTypes.width);
    break;
  }
}
References GRPD::IO::ascii, GRPD::IO::binary, buf, cellTypes, convertEndian(), GRPD::IO::Writer::format, GRPD::IO::Int32, GRPD::IO::Writer::outFile, GRPD::IO::Writer::pointsNumber, writeAscii(), and writeBinary().
Referenced by write().
writePoints()
void GRPD::IO::VtkWriter::writePoints () [private]
Definition at line 126 of file VtkWriter.cpp.
                            {
  try {
    switch (pointsInfo.type) {
    case Float32:
      outFile << "POINTS " << pointsNumber << " " << "float";
      outFile << '\n';
      switch (format) {
      case ascii:
        writeAscii(static_cast<float *>(pointsInfo.ptr), pointsInfo.width);
        break;
      case binary:
        convertEndian(buf, pointsInfo.ptr, Float32,
                      pointsNumber * pointsInfo.width);
        writeBinary(reinterpret_cast<float *>(buf), pointsInfo.width);
        break;
      }
      break;
    case Float64:
      outFile << "POINTS " << pointsNumber << " " << "double";
      outFile << '\n';
      switch (format) {
      case ascii:
        writeAscii(static_cast<double *>(pointsInfo.ptr), pointsInfo.width);
        break;
      case binary:
        convertEndian(buf, pointsInfo.ptr, Float64,
                      pointsNumber * pointsInfo.width);
        writeBinary(reinterpret_cast<double *>(buf), pointsInfo.width);
        break;
      }
      break;
    default:
      std::cout << "VtkWriter::writePoints ERROR: Points only can be written "
                   "as double/float form!\n"
                << std::endl;
      throw std::runtime_error("");
    }
  } catch (const std::exception &e) {
    std::cerr << "Error:" << e.what();
  }
}
References GRPD::IO::ascii, GRPD::IO::binary, buf, convertEndian(), GRPD::IO::Float32, GRPD::IO::Float64, GRPD::IO::Writer::format, GRPD::IO::Writer::outFile, GRPD::IO::Writer::pointsInfo, GRPD::IO::Writer::pointsNumber, writeAscii(), and writeBinary().
Referenced by write().
writePointsVariable()
void GRPD::IO::VtkWriter::writePointsVariable () [private]
Definition at line 196 of file VtkWriter.cpp.
                                    {
  outFile << "POINT_DATA " << pointsNumber;
  outFile << '\n';
  outFile << "FIELD FieldData " << pointsVariable.size();
  outFile << '\n';
  for (auto i = pointsVariable.begin(); i != pointsVariable.end(); i++) {
    outFile << i->name << " " << i->width << " " << pointsNumber << " ";
    switch (format) {
    case ascii:
      switch (i->type) {
      case Int32:
        outFile << "int";
        outFile << '\n';
        writeAscii(static_cast<int *>(i->ptr), i->width);
        break;
      case Int64:
        outFile << "long";
        outFile << '\n';
        writeAscii(static_cast<int *>(i->ptr), i->width);
        break;
      case Float32:
        outFile << "float";
        outFile << '\n';
        writeAscii(static_cast<float *>(i->ptr), i->width);
        break;
      case Float64:
        outFile << "double";
        outFile << '\n';
        writeAscii(static_cast<double *>(i->ptr), i->width);
        break;
      }
      break;
    case binary:
      switch (i->type) {
      case Int32:
        outFile << "int";
        outFile << '\n';
        convertEndian(buf, i->ptr, Int32, pointsNumber * i->width);
        writeBinary(reinterpret_cast<int *>(buf), i->width);
        break;
      case Int64:
        outFile << "long";
        outFile << '\n';
        convertEndian(buf, i->ptr, Int64, pointsNumber * i->width);
        writeBinary(reinterpret_cast<long *>(buf), i->width);
        break;
      case Float32:
        outFile << "float";
        outFile << '\n';
        convertEndian(buf, i->ptr, Float32, pointsNumber * i->width);
        writeBinary(reinterpret_cast<float *>(buf), i->width);
        break;
      case Float64:
        outFile << "double";
        outFile << '\n';
        convertEndian(buf, i->ptr, Float64, pointsNumber * i->width);
        writeBinary(reinterpret_cast<double *>(buf), i->width);
        break;
      }
      break;
    }
  }
}
References GRPD::IO::ascii, GRPD::IO::binary, buf, convertEndian(), GRPD::IO::Float32, GRPD::IO::Float64, GRPD::IO::Writer::format, GRPD::IO::Int32, GRPD::IO::Int64, GRPD::IO::Writer::outFile, GRPD::IO::Writer::pointsNumber, GRPD::IO::Writer::pointsVariable, writeAscii(), and writeBinary().
Referenced by write().
Member Data Documentation
buf
char* GRPD::IO::VtkWriter::buf [private]
Definition at line 11 of file VtkWriter.h.
Referenced by convertEndian(), setPointsNumber(), VtkWriter(), writeArrayBinary(), writeCells(), writeCellTypes(), writePoints(), writePointsVariable(), and ~VtkWriter().
cells
dataInfoStruct GRPD::IO::VtkWriter::cells [private]
Definition at line 10 of file VtkWriter.h.
Referenced by setPointsNumber(), VtkWriter(), VtkWriter(), writeCells(), and ~VtkWriter().
cellTypes
dataInfoStruct GRPD::IO::VtkWriter::cellTypes [private]
Definition at line 10 of file VtkWriter.h.
Referenced by setPointsNumber(), VtkWriter(), VtkWriter(), writeCellTypes(), and ~VtkWriter().
The documentation for this class was generated from the following files:
PDCommon/IO/include/VtkWriter.h
PDCommon/IO/src/VtkWriter.cpp