GRPD::Field::PhysicsFields Class Reference
#include <PhysicsFields.h>
Public Member Functions
PhysicsFields (const std::string &typeName="")
virtual ~PhysicsFields ()
PhysicsFields (const PhysicsFields &)=delete
PhysicsFields & operator= (const PhysicsFields &)=delete
virtual void registerFields (FieldManager &fm)=0
向 FieldManager 注册此物理问题所需的所有核心场
const std::string & getTypeName () const
获取类型名称
Protected Attributes
std::string typeName_
Detailed Description
Definition at line 21 of file PhysicsFields.h.
Constructor & Destructor Documentation
PhysicsFields() [1/2]
GRPD::Field::PhysicsFields::PhysicsFields (const std::string & typeName = "") [explicit]
Definition at line 9 of file PhysicsFields.cpp.
    : typeName_(typeName) {}
References typeName_.
Referenced by GRPD::Field::MechanicalFields::MechanicalFields(), operator=(), PhysicsFields(), and GRPD::Field::ThermalFields::ThermalFields().
~PhysicsFields()
GRPD::Field::PhysicsFields::~PhysicsFields () [virtual], [default]
PhysicsFields() [2/2]
GRPD::Field::PhysicsFields::PhysicsFields (const PhysicsFields &) [delete]
References PhysicsFields().
Member Function Documentation
getTypeName()
const std::string & GRPD::Field::PhysicsFields::getTypeName () const [inline]
获取类型名称
Definition at line 36 of file PhysicsFields.h.
{ return typeName_; }
References typeName_.
operator=()
PhysicsFields & GRPD::Field::PhysicsFields::operator= (const PhysicsFields &) [delete]
References PhysicsFields().
registerFields()
virtual void GRPD::Field::PhysicsFields::registerFields (FieldManager & fm) [pure virtual]
向 FieldManager 注册此物理问题所需的所有核心场
Parameters
fm 物理场管理器引用
Implemented in GRPD::Field::MechanicalFields, and GRPD::Field::ThermalFields.
Member Data Documentation
typeName_
std::string GRPD::Field::PhysicsFields::typeName_ [protected]
Definition at line 39 of file PhysicsFields.h.
Referenced by getTypeName(), and PhysicsFields().
The documentation for this class was generated from the following files:
PDCommon/Field/include/PhysicsFields.h
PDCommon/Field/src/PhysicsFields.cpp