GRPD::Material::MaterialRegistry Class Reference
#include <MaterialRegistry.h>
Public Member Functions
MaterialRegistry (const MaterialRegistry &)=delete
MaterialRegistry & operator= (const MaterialRegistry &)=delete
void registerMaterialType (const std::string &type, MaterialCreatorFunc creator)
Register a material type with its creator function.
std::unique_ptr< Material > createMaterial (const std::string &type, const std::string &name)
Create a material instance using the registered creator function.
Static Public Member Functions
static MaterialRegistry & getInstance ()
Private Member Functions
MaterialRegistry ()=default
~MaterialRegistry ()=default
Private Attributes
std::map< std::string, MaterialCreatorFunc > registryMap_
Detailed Description
Definition at line 26 of file MaterialRegistry.h.
Constructor & Destructor Documentation
MaterialRegistry() [1/2]
GRPD::Material::MaterialRegistry::MaterialRegistry (const MaterialRegistry &) [delete]
References MaterialRegistry().
Referenced by getInstance(), MaterialRegistry(), and operator=().
MaterialRegistry() [2/2]
GRPD::Material::MaterialRegistry::MaterialRegistry () [private], [default]
~MaterialRegistry()
GRPD::Material::MaterialRegistry::~MaterialRegistry () [private], [default]
Member Function Documentation
createMaterial()
std::unique_ptr< Material > GRPD::Material::MaterialRegistry::createMaterial (const std::string & type, const std::string & name)
Create a material instance using the registered creator function.
Parameters
type Registered material type name
name New instance name
Returns
Created Material smart pointer
Definition at line 38 of file MaterialRegistry.cpp.
                                                        {
  auto it = registryMap_.find(type);
  if (it == registryMap_.end()) {
    LOG_ERROR(
        "[MaterialRegistry] Create material failed: unknown material type '" +
        type + "' !");
    throw std::runtime_error("Unknown material type: " + type);
  }
  LOG_INFO("[MaterialRegistry] Using factory to create material: " + name +
           " (type: " + type + ")");
  return it->second(name);
}
References LOG_ERROR, LOG_INFO, and registryMap_.
Referenced by GRPD::Engine::SolverEngine::InitMaterialPD().
getInstance()
MaterialRegistry & GRPD::Material::MaterialRegistry::getInstance () [static]
Definition at line 14 of file MaterialRegistry.cpp.
                                                {
  static MaterialRegistry instance;
  return instance;
}
References MaterialRegistry().
Referenced by GRPD::Engine::SolverEngine::InitMaterialPD().
operator=()
MaterialRegistry & GRPD::Material::MaterialRegistry::operator= (const MaterialRegistry &) [delete]
References MaterialRegistry().
registerMaterialType()
void GRPD::Material::MaterialRegistry::registerMaterialType (const std::string & type, MaterialCreatorFunc creator)
Register a material type with its creator function.
Parameters
type Material type name (e.g., "Elastic", "ThermalMat")
creator Function to create the material instance
Definition at line 22 of file MaterialRegistry.cpp.
                                                                         {
  if (registryMap_.find(type) != registryMap_.end()) {
    LOG_WARNING("[MaterialRegistry] Material type '" + type +
                "' has been registry, overwrite it.");
  } else {
    LOG_INFO("[MaterialRegistry] Material type '" + type +
             "' has been registry.");
  }
  registryMap_[type] = creator;
}
References LOG_INFO, LOG_WARNING, and registryMap_.
Member Data Documentation
registryMap_
std::map<std::string, MaterialCreatorFunc> GRPD::Material::MaterialRegistry::registryMap_ [private]
Definition at line 58 of file MaterialRegistry.h.
Referenced by createMaterial(), and registerMaterialType().
The documentation for this class was generated from the following files:
PDCommon/Material/include/MaterialRegistry.h
PDCommon/Material/src/MaterialRegistry.cpp