GRPD::Initial::NeighborList Class Reference
#include <NeighborList.h>
Public Member Functions
NeighborList ()=default
~NeighborList ()=default
NeighborList (const NeighborList &)=delete
NeighborList & operator= (const NeighborList &)=delete
void buildNeighbors (const GRPD::Model::ParticleManager &mgr, double horizon)
构建近邻列表 (暴力搜索版本 O(N^2))
const std::vector< int > & getNeighbors (int particleId) const
获取指定粒子的邻居 ID 列表
size_t size () const
获取总粒子数（也就是列表的外层尺寸）
double getHorizon () const
获取构建时使用的邻域半径 delta
size_t getNeighborCount (int particleId) const
获取指定粒子的邻居数量
void clear ()
清空数据
Private Attributes
std::vector< std::vector< int > > neighbors_
double horizon_ {0.0}
Detailed Description
Definition at line 21 of file NeighborList.h.
Constructor & Destructor Documentation
NeighborList() [1/2]
GRPD::Initial::NeighborList::NeighborList () [default]
Referenced by NeighborList(), and operator=().
~NeighborList()
GRPD::Initial::NeighborList::~NeighborList () [default]
NeighborList() [2/2]
GRPD::Initial::NeighborList::NeighborList (const NeighborList &) [delete]
References NeighborList().
Member Function Documentation
buildNeighbors()
void GRPD::Initial::NeighborList::buildNeighbors (const GRPD::Model::ParticleManager & mgr, double horizon)
构建近邻列表 (暴力搜索版本 O(N^2))
Parameters
mgr ParticleManager 实例，包含所有点位置
horizon 邻域半径 delta
Definition at line 10 of file NeighborList.cpp.
                                                                                     {
    this->horizon_ = horizon;
    size_t numParticles = mgr.getTotalParticles();
    LOG_INFO("[NeighborList] Starting neighbor search for " + std::to_string(numParticles) +
             " particles with horizon = " + std::to_string(horizon));
    // 1. 初始化列表
    neighbors_.assign(numParticles, std::vector<int>());
    double h2 = horizon * horizon;
    // 2. 双重循环暴力搜索 (并利用 OpenMP 加速)
    // 注意：PD 键是对称的，但为了代码简单和避免复杂的 atomic，先使用全量遍历
    // 在 12w 规模下，并行化非常重要
    #pragma omp parallel for schedule(dynamic, 64)
    for (int i = 0; i < static_cast<int>(numParticles); ++i) {
        const auto& p_i = mgr.getParticle(i);
        const auto& pos_i = p_i.getCoords();
        // 预分配内层空间可以减少内存重分配开销 (估算 PD 邻居数约为 50-100)
        neighbors_[i].reserve(100);
        for (int j = 0; j < static_cast<int>(numParticles); ++j) {
            if (i == j) continue;
            const auto& p_j = mgr.getParticle(j);
            const auto& pos_j = p_j.getCoords();
            double dx = pos_j[0] - pos_i[0];
            double dy = pos_j[1] - pos_i[1];
            double dz = pos_j[2] - pos_i[2];
            double dist2 = dx*dx + dy*dy + dz*dz;
            if (dist2 <= h2) {
                neighbors_[i].push_back(j);
            }
        }
    }
    size_t totalBonds = 0;
    for (const auto& list : neighbors_) {
        totalBonds += list.size();
    }
    LOG_INFO("[NeighborList] Neighbor search complete. Total bonds found: " +
             std::to_string(totalBonds));
}
References GRPD::Model::Particle::getCoords(), GRPD::Model::ParticleManager::getParticle(), GRPD::Model::ParticleManager::getTotalParticles(), horizon_, LOG_INFO, and neighbors_.
clear()
void GRPD::Initial::NeighborList::clear ()
清空数据
Definition at line 69 of file NeighborList.cpp.
                         {
    neighbors_.clear();
}
References neighbors_.
getHorizon()
double GRPD::Initial::NeighborList::getHorizon () const
获取构建时使用的邻域半径 delta
Definition at line 73 of file NeighborList.cpp.
                                      {
    return horizon_;
}
References horizon_.
getNeighborCount()
size_t GRPD::Initial::NeighborList::getNeighborCount (int particleId) const
获取指定粒子的邻居数量
Definition at line 65 of file NeighborList.cpp.
                                                          {
    return neighbors_[particleId].size();
}
References neighbors_.
getNeighbors()
const std::vector< int > & GRPD::Initial::NeighborList::getNeighbors (int particleId) const
获取指定粒子的邻居 ID 列表
Parameters
particleId 粒子全局索引
Returns
const std::vector<int>& 邻居 ID 数组
Definition at line 57 of file NeighborList.cpp.
                                                                     {
    return neighbors_[particleId];
}
References neighbors_.
operator=()
NeighborList & GRPD::Initial::NeighborList::operator= (const NeighborList &) [delete]
References NeighborList().
size()
size_t GRPD::Initial::NeighborList::size () const
获取总粒子数（也就是列表的外层尺寸）
Definition at line 61 of file NeighborList.cpp.
                                {
    return neighbors_.size();
}
References neighbors_.
Member Data Documentation
horizon_
double GRPD::Initial::NeighborList::horizon_ {0.0} [private]
Definition at line 67 of file NeighborList.h.
{0.0}; // 邻域半径
Referenced by buildNeighbors(), and getHorizon().
neighbors_
std::vector<std::vector<int> > GRPD::Initial::NeighborList::neighbors_ [private]
Definition at line 66 of file NeighborList.h.
Referenced by buildNeighbors(), clear(), getNeighborCount(), getNeighbors(), and size().
The documentation for this class was generated from the following files:
PDCommon/Initial/include/NeighborList.h
PDCommon/Initial/src/NeighborList.cpp