GRPD::BC::BCManager Class Reference
#include <BCManager.h>
Public Member Functions
BCManager ()=default
~BCManager ()=default
BCManager (const BCManager &)=delete
BCManager & operator= (const BCManager &)=delete
BCManager (BCManager &&)=default
BCManager & operator= (BCManager &&)=default
void addBC (std::unique_ptr< BC > bc)
添加一个边界条件实例（独占所有权）
void applyAll ()
批量施加所有边界条件
void applySources ()
仅施加源项型边界条件（如热流、对流）
void applyConstraints ()
仅施加约束型边界条件（如固定温度）
size_t size () const
获取当前管理的边界条件总数
void clear ()
清空所有边界条件
Private Attributes
std::vector< std::unique_ptr< BC > > bcs_
Detailed Description
Definition at line 18 of file BCManager.h.
Constructor & Destructor Documentation
BCManager() [1/3]
GRPD::BC::BCManager::BCManager () [default]
Referenced by BCManager(), BCManager(), operator=(), and operator=().
~BCManager()
GRPD::BC::BCManager::~BCManager () [default]
BCManager() [2/3]
GRPD::BC::BCManager::BCManager (const BCManager &) [delete]
References BCManager().
BCManager() [3/3]
GRPD::BC::BCManager::BCManager (BCManager &&) [default]
References BCManager().
Member Function Documentation
addBC()
void GRPD::BC::BCManager::addBC (std::unique_ptr< BC > bc)
添加一个边界条件实例（独占所有权）
Parameters
bc 边界条件实例的 unique_ptr
Definition at line 9 of file BCManager.cpp.
                                          {
    bcs_.push_back(std::move(bc));
}
References bcs_.
applyAll()
void GRPD::BC::BCManager::applyAll ()
批量施加所有边界条件
Definition at line 13 of file BCManager.cpp.
                         {
    for (auto &bc : bcs_) {
        bc->apply();
    }
}
References bcs_.
applyConstraints()
void GRPD::BC::BCManager::applyConstraints ()
仅施加约束型边界条件（如固定温度）
Definition at line 27 of file BCManager.cpp.
                                 {
    for (auto &bc : bcs_) {
        if (bc->isConstraint()) {
            bc->apply();
        }
    }
}
References bcs_.
applySources()
void GRPD::BC::BCManager::applySources ()
仅施加源项型边界条件（如热流、对流）
Definition at line 19 of file BCManager.cpp.
                             {
    for (auto &bc : bcs_) {
        if (!bc->isConstraint()) {
            bc->apply();
        }
    }
}
References bcs_.
clear()
void GRPD::BC::BCManager::clear ()
清空所有边界条件
Definition at line 37 of file BCManager.cpp.
{ bcs_.clear(); }
References bcs_.
operator=() [1/2]
BCManager & GRPD::BC::BCManager::operator= (BCManager &&) [default]
References BCManager().
operator=() [2/2]
BCManager & GRPD::BC::BCManager::operator= (const BCManager &) [delete]
References BCManager().
size()
size_t GRPD::BC::BCManager::size () const
获取当前管理的边界条件总数
Definition at line 35 of file BCManager.cpp.
{ return bcs_.size(); }
References bcs_.
Member Data Documentation
bcs_
std::vector<std::unique_ptr<BC> > GRPD::BC::BCManager::bcs_ [private]
Definition at line 54 of file BCManager.h.
Referenced by addBC(), applyAll(), applyConstraints(), applySources(), clear(), and size().
The documentation for this class was generated from the following files:
PDCommon/BC/include/BCManager.h
PDCommon/BC/src/BCManager.cpp