GRPD::Core::PDSimulater Class Reference
#include <PDSimulater.h>
Public Member Functions
PDSimulater (const std::string &name)
构造函数，初始化一个全新的仿真模型上下文
~PDSimulater ()=default
PDSimulater (const PDSimulater &)=delete
PDSimulater & operator= (const PDSimulater &)=delete
PDSimulater (PDSimulater &&)=default
PDSimulater & operator= (PDSimulater &&)=default
const std::string & getName () const
获取模型名称
void setName (const std::string &name)
设置模型名称
GRPD::Model::ParticleManager & getParticleManager ()
获取粒子管理器引用（非 const，用于求解和初始化）
const GRPD::Model::ParticleManager & getParticleManager () const
GRPD::Material::MaterialManager & getMaterialManager ()
获取材料管理器引用（非 const，用于绑定和求解）
const GRPD::Material::MaterialManager & getMaterialManager () const
GRPD::Field::FieldManager & getFieldManager ()
获取物理场管理器引用
const GRPD::Field::FieldManager & getFieldManager () const
void createNeighborList (const GRPD::Model::ParticleManager &mgr, double horizon)
bool hasNeighborList () const
GRPD::Initial::NeighborList & getNeighborList ()
const GRPD::Initial::NeighborList & getNeighborList () const
GRPD::BC::BCManager & getBCManager ()
const GRPD::BC::BCManager & getBCManager () const
Private Attributes
std::string name_
GRPD::Model::ParticleManager particleManager_
GRPD::Material::MaterialManager materialManager_
GRPD::Field::FieldManager fieldManager_
std::unique_ptr< GRPD::Initial::NeighborList > neighborList_
GRPD::BC::BCManager bcManager_
Detailed Description
Definition at line 22 of file PDSimulater.h.
Constructor & Destructor Documentation
PDSimulater() [1/3]
GRPD::Core::PDSimulater::PDSimulater (const std::string & name) [explicit]
构造函数，初始化一个全新的仿真模型上下文
Parameters
name 模型名称，用于标识和日志输出
Definition at line 11 of file PDSimulater.cpp.
                                              : name_(name) {
  LOG_INFO(std::string("[PDSimulater] Start: ") + name_);
}
References LOG_INFO, and name_.
Referenced by operator=(), operator=(), PDSimulater(), and PDSimulater().
~PDSimulater()
GRPD::Core::PDSimulater::~PDSimulater () [default]
PDSimulater() [2/3]
GRPD::Core::PDSimulater::PDSimulater (const PDSimulater &) [delete]
References PDSimulater().
PDSimulater() [3/3]
GRPD::Core::PDSimulater::PDSimulater (PDSimulater &&) [default]
References PDSimulater().
Member Function Documentation
createNeighborList()
void GRPD::Core::PDSimulater::createNeighborList (const GRPD::Model::ParticleManager & mgr, double horizon)
Definition at line 15 of file PDSimulater.cpp.
                                                    {
  neighborList_ = std::make_unique<GRPD::Initial::NeighborList>();
  neighborList_->buildNeighbors(mgr, horizon);
}
References neighborList_.
getBCManager() [1/2]
GRPD::BC::BCManager & GRPD::Core::PDSimulater::getBCManager () [inline]
Definition at line 82 of file PDSimulater.h.
{ return bcManager_; }
References bcManager_.
Referenced by GRPD::IO::GrpdReader::readLoads().
getBCManager() [2/2]
const GRPD::BC::BCManager & GRPD::Core::PDSimulater::getBCManager () const [inline]
Definition at line 83 of file PDSimulater.h.
{ return bcManager_; }
References bcManager_.
getFieldManager() [1/2]
GRPD::Field::FieldManager & GRPD::Core::PDSimulater::getFieldManager () [inline]
获取物理场管理器引用
Definition at line 63 of file PDSimulater.h.
{ return fieldManager_; }
References fieldManager_.
Referenced by GRPD::IO::GrpdReader::readLoads().
getFieldManager() [2/2]
const GRPD::Field::FieldManager & GRPD::Core::PDSimulater::getFieldManager () const [inline]
Definition at line 64 of file PDSimulater.h.
                                                       {
    return fieldManager_;
  }
References fieldManager_.
getMaterialManager() [1/2]
GRPD::Material::MaterialManager & GRPD::Core::PDSimulater::getMaterialManager () [inline]
获取材料管理器引用（非 const，用于绑定和求解）
Definition at line 51 of file PDSimulater.h.
                                                    {
    return materialManager_;
  }
References materialManager_.
getMaterialManager() [2/2]
const GRPD::Material::MaterialManager & GRPD::Core::PDSimulater::getMaterialManager () const [inline]
Definition at line 54 of file PDSimulater.h.
                                                                {
    return materialManager_;
  }
References materialManager_.
getName()
const std::string & GRPD::Core::PDSimulater::getName () const [inline]
获取模型名称
Definition at line 37 of file PDSimulater.h.
{ return name_; }
References name_.
getNeighborList() [1/2]
GRPD::Initial::NeighborList & GRPD::Core::PDSimulater::getNeighborList () [inline]
Definition at line 74 of file PDSimulater.h.
{ return *neighborList_; }
References neighborList_.
getNeighborList() [2/2]
const GRPD::Initial::NeighborList & GRPD::Core::PDSimulater::getNeighborList () const [inline]
Definition at line 75 of file PDSimulater.h.
                                                         {
    return *neighborList_;
  }
References neighborList_.
getParticleManager() [1/2]
GRPD::Model::ParticleManager & GRPD::Core::PDSimulater::getParticleManager () [inline]
获取粒子管理器引用（非 const，用于求解和初始化）
Definition at line 43 of file PDSimulater.h.
                                                 {
    return particleManager_;
  }
References particleManager_.
getParticleManager() [2/2]
const GRPD::Model::ParticleManager & GRPD::Core::PDSimulater::getParticleManager () const [inline]
Definition at line 46 of file PDSimulater.h.
                                                             {
    return particleManager_;
  }
References particleManager_.
hasNeighborList()
bool GRPD::Core::PDSimulater::hasNeighborList () const [inline]
Definition at line 73 of file PDSimulater.h.
{ return neighborList_ != nullptr; }
References neighborList_.
operator=() [1/2]
PDSimulater & GRPD::Core::PDSimulater::operator= (const PDSimulater &) [delete]
References PDSimulater().
operator=() [2/2]
PDSimulater & GRPD::Core::PDSimulater::operator= (PDSimulater &&) [default]
References PDSimulater().
setName()
void GRPD::Core::PDSimulater::setName (const std::string & name) [inline]
设置模型名称
Definition at line 40 of file PDSimulater.h.
{ name_ = name; }
References name_.
Member Data Documentation
bcManager_
GRPD::BC::BCManager GRPD::Core::PDSimulater::bcManager_ [private]
Definition at line 94 of file PDSimulater.h.
Referenced by getBCManager(), and getBCManager().
fieldManager_
GRPD::Field::FieldManager GRPD::Core::PDSimulater::fieldManager_ [private]
Definition at line 89 of file PDSimulater.h.
Referenced by getFieldManager(), and getFieldManager().
materialManager_
GRPD::Material::MaterialManager GRPD::Core::PDSimulater::materialManager_ [private]
Definition at line 88 of file PDSimulater.h.
Referenced by getMaterialManager(), and getMaterialManager().
name_
std::string GRPD::Core::PDSimulater::name_ [private]
Definition at line 86 of file PDSimulater.h.
Referenced by getName(), PDSimulater(), and setName().
neighborList_
std::unique_ptr<GRPD::Initial::NeighborList> GRPD::Core::PDSimulater::neighborList_ [private]
Definition at line 92 of file PDSimulater.h.
Referenced by createNeighborList(), getNeighborList(), getNeighborList(), and hasNeighborList().
particleManager_
GRPD::Model::ParticleManager GRPD::Core::PDSimulater::particleManager_ [private]
Definition at line 87 of file PDSimulater.h.
Referenced by getParticleManager(), and getParticleManager().
The documentation for this class was generated from the following files:
PDCommon/Core/include/PDSimulater.h
PDCommon/Core/src/PDSimulater.cpp