GRPD::Material::Material Class Reference
#include <Material.h>
Public Member Functions
Material (const std::string &name="")
构造函数
virtual ~Material ()=default
Material (const Material &)=delete
Material & operator= (const Material &)=delete
const std::string & getName () const
获取当前材料实例名称
void setName (const std::string &name)
设置名字
int getMatId () const
获取/设置 MatID
void setMatId (int id)
virtual void initialize (const YAML::Node &matNode)
初始化材料参数或状态变量
virtual void allocateStateVariables (GRPD::Field::FieldManager &fm)
分配材料私有的状态变量场 子类覆盖此方法，向 FieldManager 注册材料所需的状态变量 例如：ThermalMat 注册 HeatFlux，ElasticMat 注册 Stress/Strain
virtual void evaluate ()=0
计算力态或更新本构关系 (子类需具体实现) 注意：后续应结合Particle对象的属性（如状态变量state_vars等）传入进行计算
Protected Attributes
std::string name_
int matId_
Detailed Description
Definition at line 20 of file Material.h.
Constructor & Destructor Documentation
Material() [1/2]
GRPD::Material::Material::Material (const std::string & name = "") [explicit]
构造函数
Parameters
name 材料实例的唯一名称
Definition at line 10 of file Material.cpp.
: name_(name), matId_(-1) {}
References matId_, and name_.
Referenced by Material(), operator=(), and GRPD::Material::ThermalMat::ThermalMat().
~Material()
virtual GRPD::Material::Material::~Material () [virtual], [default]
Material() [2/2]
GRPD::Material::Material::Material (const Material &) [delete]
References Material().
Member Function Documentation
allocateStateVariables()
void GRPD::Material::Material::allocateStateVariables (GRPD::Field::FieldManager & fm) [virtual]
分配材料私有的状态变量场 子类覆盖此方法，向 FieldManager 注册材料所需的状态变量 例如：ThermalMat 注册 HeatFlux，ElasticMat 注册 Stress/Strain
Parameters
fm 物理场管理器引用
Reimplemented in GRPD::Material::ThermalMat.
Definition at line 24 of file Material.cpp.
                                                               {
  // 默认空实现，子类覆盖以注册材料私有的状态变量场
  // 例如：ThermalMat 注册 HeatFlux, ElasticMat 注册 Stress/Strain
}
evaluate()
virtual void GRPD::Material::Material::evaluate () [pure virtual]
计算力态或更新本构关系 (子类需具体实现) 注意：后续应结合Particle对象的属性（如状态变量state_vars等）传入进行计算
Implemented in GRPD::Material::ThermalMat.
getMatId()
int GRPD::Material::Material::getMatId () const
获取/设置 MatID
Definition at line 16 of file Material.cpp.
{ return matId_; }
References matId_.
getName()
const std::string & GRPD::Material::Material::getName () const
获取当前材料实例名称
Definition at line 12 of file Material.cpp.
{ return name_; }
References name_.
initialize()
void GRPD::Material::Material::initialize (const YAML::Node & matNode) [virtual]
初始化材料参数或状态变量
Parameters
matNode 对应于本材料的 YAML 配置节点
Reimplemented in GRPD::Material::ThermalMat.
Definition at line 20 of file Material.cpp.
                                                 {
  // 默认空实现，子类可覆盖以处理具体的 YAML 数据
}
operator=()
Material & GRPD::Material::Material::operator= (const Material &) [delete]
References Material().
setMatId()
void GRPD::Material::Material::setMatId (int id)
Definition at line 18 of file Material.cpp.
{ matId_ = id; }
References matId_.
setName()
void GRPD::Material::Material::setName (const std::string & name)
设置名字
Definition at line 14 of file Material.cpp.
{ name_ = name; }
References name_.
Member Data Documentation
matId_
int GRPD::Material::Material::matId_ [protected]
Definition at line 58 of file Material.h.
Referenced by getMatId(), Material(), and setMatId().
name_
std::string GRPD::Material::Material::name_ [protected]
Definition at line 57 of file Material.h.
Referenced by GRPD::Material::ThermalMat::allocateStateVariables(), getName(), GRPD::Material::ThermalMat::initialize(), Material(), and setName().
The documentation for this class was generated from the following files:
PDCommon/Material/include/Material.h
PDCommon/Material/src/Material.cpp