GRPD::Field::TypedField< T > Class Template Reference
模板物理场类
#include <TypedField.h>
Public Member Functions
TypedField (const std::string &name, int dim=1)
构造函数
~TypedField () override=default
TypedField (const TypedField &)=delete
TypedField & operator= (const TypedField &)=delete
TypedField (TypedField &&)=default
TypedField & operator= (TypedField &&)=default
void resize (size_t numParticles) override
按粒子总数分配内存，初始化为零值 实际分配长度 = numParticles * dim_
size_t size () const override
当前存储的粒子数量
void clearToZero () override
将所有数据清零
double * rawPtr () override
获取底层 double* 裸指针（用于 VTK 输出等通用接口）
const double * rawPtr () const override
获取底层 const double* 裸指针
T get (int id, int comp=0) const
获取指定粒子、指定分量的值
void set (int id, T val, int comp=0)
设置指定粒子、指定分量的值
void add (int id, T val, int comp=0)
累加指定粒子、指定分量的值（适用于力/变化率等可叠加量）
T * dataPtr ()
获取类型安全的数据裸指针
const T * dataPtr () const
获取类型安全的 const 数据裸指针
std::vector< T > & getData ()
获取底层 std::vector 引用（高级用途）
const std::vector< T > & getData () const
Public Member Functions inherited from GRPD::Field::Field
Field (const std::string &name, int dim=1)
构造函数
virtual ~Field ()=default
Field (const Field &)=delete
Field & operator= (const Field &)=delete
Field (Field &&)=default
Field & operator= (Field &&)=default
const std::string & getName () const
获取物理场名称
int getDim () const
获取每个粒子的分量维度（标量=1, 矢量=3, 张量=9）
Private Attributes
std::vector< T > data_
Additional Inherited Members
Protected Attributes inherited from GRPD::Field::Field
std::string name_
int dim_
Detailed Description
template<typename T = double>
class GRPD::Field::TypedField< T >
模板物理场类
Template Parameters
T 数据类型，默认为 double（支持 int 等扩展）
Definition at line 21 of file TypedField.h.
Constructor & Destructor Documentation
TypedField() [1/3]
template<typename T = double>
GRPD::Field::TypedField< T >::TypedField (const std::string & name, int dim = 1) [inline], [explicit]
构造函数
Parameters
name 物理场名称（如 "Temperature", "Displacement"）
dim 每个粒子的分量数（标量=1, 矢量=3）
Definition at line 26 of file TypedField.h.
        : Field(name, dim) {}
References GRPD::Field::Field::Field().
Referenced by operator=(), operator=(), TypedField(), and TypedField().
~TypedField()
template<typename T = double>
GRPD::Field::TypedField< T >::~TypedField () [override], [default]
TypedField() [2/3]
template<typename T = double>
GRPD::Field::TypedField< T >::TypedField (const TypedField< T > &) [delete]
References TypedField().
TypedField() [3/3]
template<typename T = double>
GRPD::Field::TypedField< T >::TypedField (TypedField< T > &&) [default]
References TypedField().
Member Function Documentation
add()
template<typename T = double>
void GRPD::Field::TypedField< T >::add (int id, T val, int comp = 0) [inline]
累加指定粒子、指定分量的值（适用于力/变化率等可叠加量）
Definition at line 84 of file TypedField.h.
                                          {
        data_[static_cast<size_t>(id) * dim_ + comp] += val;
    }
References data_, and GRPD::Field::Field::dim_.
clearToZero()
template<typename T = double>
void GRPD::Field::TypedField< T >::clearToZero () [inline], [override], [virtual]
将所有数据清零
Implements GRPD::Field::Field.
Definition at line 53 of file TypedField.h.
                                {
        std::fill(data_.begin(), data_.end(), T{});
    }
References data_.
dataPtr() [1/2]
template<typename T = double>
T * GRPD::Field::TypedField< T >::dataPtr () [inline]
获取类型安全的数据裸指针
Definition at line 93 of file TypedField.h.
{ return data_.data(); }
References data_.
dataPtr() [2/2]
template<typename T = double>
const T * GRPD::Field::TypedField< T >::dataPtr () const [inline]
获取类型安全的 const 数据裸指针
Definition at line 96 of file TypedField.h.
{ return data_.data(); }
References data_.
get()
template<typename T = double>
T GRPD::Field::TypedField< T >::get (int id, int comp = 0) const [inline]
获取指定粒子、指定分量的值
Parameters
id 粒子 ID（全局索引）
comp 分量索引（标量场为 0，矢量场为 0/1/2）
Definition at line 74 of file TypedField.h.
                                      {
        return data_[static_cast<size_t>(id) * dim_ + comp];
    }
References data_, and GRPD::Field::Field::dim_.
Referenced by GRPD::Field::FieldManager::registerField().
getData() [1/2]
template<typename T = double>
std::vector< T > & GRPD::Field::TypedField< T >::getData () [inline]
获取底层 std::vector 引用（高级用途）
Definition at line 99 of file TypedField.h.
{ return data_; }
References data_.
getData() [2/2]
template<typename T = double>
const std::vector< T > & GRPD::Field::TypedField< T >::getData () const [inline]
Definition at line 100 of file TypedField.h.
{ return data_; }
References data_.
operator=() [1/2]
template<typename T = double>
TypedField & GRPD::Field::TypedField< T >::operator= (const TypedField< T > &) [delete]
References TypedField().
operator=() [2/2]
template<typename T = double>
TypedField & GRPD::Field::TypedField< T >::operator= (TypedField< T > &&) [default]
References TypedField().
rawPtr() [1/2]
template<typename T = double>
const double * GRPD::Field::TypedField< T >::rawPtr () const [inline], [override], [virtual]
获取底层 const double* 裸指针
Implements GRPD::Field::Field.
Definition at line 63 of file TypedField.h.
                                          {
        return reinterpret_cast<const double *>(data_.data());
    }
References data_.
rawPtr() [2/2]
template<typename T = double>
double * GRPD::Field::TypedField< T >::rawPtr () [inline], [override], [virtual]
获取底层 double* 裸指针（用于 VTK 输出等通用接口）
Implements GRPD::Field::Field.
Definition at line 58 of file TypedField.h.
                              {
        return reinterpret_cast<double *>(data_.data());
    }
References data_.
resize()
template<typename T = double>
void GRPD::Field::TypedField< T >::resize (size_t numParticles) [inline], [override], [virtual]
按粒子总数分配内存，初始化为零值 实际分配长度 = numParticles * dim_
Implements GRPD::Field::Field.
Definition at line 43 of file TypedField.h.
                                              {
        data_.assign(numParticles * static_cast<size_t>(dim_), T{});
    }
References data_, and GRPD::Field::Field::dim_.
set()
template<typename T = double>
void GRPD::Field::TypedField< T >::set (int id, T val, int comp = 0) [inline]
设置指定粒子、指定分量的值
Definition at line 79 of file TypedField.h.
                                          {
        data_[static_cast<size_t>(id) * dim_ + comp] = val;
    }
References data_, and GRPD::Field::Field::dim_.
size()
template<typename T = double>
size_t GRPD::Field::TypedField< T >::size () const [inline], [override], [virtual]
当前存储的粒子数量
Implements GRPD::Field::Field.
Definition at line 48 of file TypedField.h.
                                 {
        return dim_ > 0 ? data_.size() / static_cast<size_t>(dim_) : 0;
    }
References data_, and GRPD::Field::Field::dim_.
Member Data Documentation
data_
template<typename T = double>
std::vector<T> GRPD::Field::TypedField< T >::data_ [private]
Definition at line 103 of file TypedField.h.
Referenced by add(), clearToZero(), dataPtr(), dataPtr(), get(), getData(), getData(), rawPtr(), rawPtr(), resize(), set(), and size().
The documentation for this class was generated from the following file:
PDCommon/Field/include/TypedField.h