GRPD::BC::BC Class Reference
#include <BC.h>
Public Member Functions
BC (const std::string &name="")
构造函数
virtual ~BC ()=default
BC (const BC &)=delete
BC & operator= (const BC &)=delete
const std::string & getName () const
获取边界条件名称
void setName (const std::string &name)
设置名称
virtual void initialize (GRPD::Field::FieldManager &fieldManager, int particleId, const std::vector< double > &values)=0
初始化接口：注入物理场管理器、粒子 ID 和参数值
virtual void apply ()=0
施加边界条件的核心虚函数 每个具体的派生类将实现自己的施加逻辑
virtual bool isConstraint () const
标识是否为约束型边界（如固定温度），用于在时间积分后重新施加
Protected Attributes
std::string name_
Detailed Description
Definition at line 22 of file BC.h.
Constructor & Destructor Documentation
BC() [1/2]
GRPD::BC::BC::BC (const std::string & name = "") [explicit]
构造函数
Parameters
name 边界条件实例的唯一名称
Definition at line 9 of file BC.cpp.
: name_(name) {}
References name_.
Referenced by BC(), operator=(), and GRPD::BC::ThermalBC::ThermalBC().
~BC()
virtual GRPD::BC::BC::~BC () [virtual], [default]
BC() [2/2]
GRPD::BC::BC::BC (const BC &) [delete]
References BC().
Member Function Documentation
apply()
virtual void GRPD::BC::BC::apply () [pure virtual]
施加边界条件的核心虚函数 每个具体的派生类将实现自己的施加逻辑
Implemented in GRPD::BC::ConvectionBC, GRPD::BC::HeatFluxBC, and GRPD::BC::TemperatureBC.
getName()
const std::string & GRPD::BC::BC::getName () const
获取边界条件名称
Definition at line 11 of file BC.cpp.
{ return name_; }
References name_.
initialize()
virtual void GRPD::BC::BC::initialize (GRPD::Field::FieldManager & fieldManager, int particleId, const std::vector< double > & values) [pure virtual]
初始化接口：注入物理场管理器、粒子 ID 和参数值
Parameters
fieldManager 物理场管理器引用（通过它获取各物理场）
particleId 粒子 ID
values 参数值列表
Implemented in GRPD::BC::ConvectionBC, GRPD::BC::HeatFluxBC, and GRPD::BC::TemperatureBC.
isConstraint()
virtual bool GRPD::BC::BC::isConstraint () const [inline], [virtual]
标识是否为约束型边界（如固定温度），用于在时间积分后重新施加
Reimplemented in GRPD::BC::TemperatureBC.
Definition at line 53 of file BC.h.
{ return false; }
operator=()
BC & GRPD::BC::BC::operator= (const BC &) [delete]
References BC().
setName()
void GRPD::BC::BC::setName (const std::string & name)
设置名称
Definition at line 13 of file BC.cpp.
{ name_ = name; }
References name_.
Member Data Documentation
name_
std::string GRPD::BC::BC::name_ [protected]
Definition at line 56 of file BC.h.
Referenced by BC(), getName(), and setName().
The documentation for this class was generated from the following files:
PDCommon/BC/include/BC.h
PDCommon/BC/src/BC.cpp