GRPD::Field::FieldRegistry Class Reference
#include <FieldRegistry.h>
Public Member Functions
FieldRegistry (const FieldRegistry &)=delete
FieldRegistry & operator= (const FieldRegistry &)=delete
void registerFieldType (const std::string &type, FieldCreatorFunc creator)
注册一个物理场类型及其工厂函数
std::unique_ptr< Field > createField (const std::string &type, const std::string &name)
使用注册的工厂函数创建物理场实例
Static Public Member Functions
static FieldRegistry & getInstance ()
Private Member Functions
FieldRegistry ()=default
~FieldRegistry ()=default
Private Attributes
std::map< std::string, FieldCreatorFunc > registryMap_
Detailed Description
Definition at line 26 of file FieldRegistry.h.
Constructor & Destructor Documentation
FieldRegistry() [1/2]
GRPD::Field::FieldRegistry::FieldRegistry (const FieldRegistry &) [delete]
References FieldRegistry().
Referenced by FieldRegistry(), getInstance(), and operator=().
FieldRegistry() [2/2]
GRPD::Field::FieldRegistry::FieldRegistry () [private], [default]
~FieldRegistry()
GRPD::Field::FieldRegistry::~FieldRegistry () [private], [default]
Member Function Documentation
createField()
std::unique_ptr< Field > GRPD::Field::FieldRegistry::createField (const std::string & type, const std::string & name)
使用注册的工厂函数创建物理场实例
Parameters
type 已注册的类型名
name 新实例名称
Returns
创建的 Field 智能指针
Definition at line 37 of file FieldRegistry.cpp.
                                                                           {
  auto it = registryMap_.find(type);
  if (it == registryMap_.end()) {
    LOG_ERROR("[FieldRegistry] Create Field failed: unknown type '" + type +
              "'!");
    throw std::runtime_error("Unknown Field type: " + type);
  }
  return it->second(name);
}
References LOG_ERROR, and registryMap_.
Referenced by GRPD::Field::FieldManager::createField().
getInstance()
FieldRegistry & GRPD::Field::FieldRegistry::getInstance () [static]
Definition at line 15 of file FieldRegistry.cpp.
                                          {
  static FieldRegistry instance;
  return instance;
}
References FieldRegistry().
Referenced by GRPD::Field::FieldManager::createField().
operator=()
FieldRegistry & GRPD::Field::FieldRegistry::operator= (const FieldRegistry &) [delete]
References FieldRegistry().
registerFieldType()
void GRPD::Field::FieldRegistry::registerFieldType (const std::string & type, FieldCreatorFunc creator)
注册一个物理场类型及其工厂函数
Parameters
type 物理场类型名（如 "ScalarField", "VectorField"）
creator 创建该类型实例的工厂函数
Definition at line 23 of file FieldRegistry.cpp.
                                                                 {
  if (registryMap_.find(type) != registryMap_.end()) {
    LOG_WARNING("[FieldRegistry] Field type '" + type +
                "' already registered, overwriting.");
  } else {
    LOG_INFO("[FieldRegistry] Field type '" + type + "' registered.");
  }
  registryMap_[type] = creator;
}
References LOG_INFO, LOG_WARNING, and registryMap_.
Member Data Documentation
registryMap_
std::map<std::string, FieldCreatorFunc> GRPD::Field::FieldRegistry::registryMap_ [private]
Definition at line 58 of file FieldRegistry.h.
Referenced by createField(), and registerFieldType().
The documentation for this class was generated from the following files:
PDCommon/Field/include/FieldRegistry.h
PDCommon/Field/src/FieldRegistry.cpp