GRPD::Engine::SolverEngine Class Reference
#include <SolverEngine.h>
Public Member Functions
SolverEngine ()
~SolverEngine ()=default
SolverEngine (const SolverEngine &)=delete
SolverEngine & operator= (const SolverEngine &)=delete
void Initialize (const std::string &yamlPath="../../Input/PD.yaml")
初始化整个仿真工程（解析参数、生成网格、分配材料等）
void Solve ()
启动主求解循环
void Output ()
将当前步的结果导出到文件
Private Member Functions
void InitModelPD ()
void InitMaterialPD ()
void InitFieldsPD ()
void InitConditionsPD ()
void SolvePD ()
void OutputPD ()
Private Attributes
GRPD::Core::PDSimulater pdContext_
Detailed Description
Definition at line 16 of file SolverEngine.h.
Constructor & Destructor Documentation
SolverEngine() [1/2]
GRPD::Engine::SolverEngine::SolverEngine ()
Definition at line 11 of file SolverEngine.cpp.
                           : pdContext_("GRPD_Model") {
  LOG_INFO("==================================================");
  LOG_INFO(" GRPD Solver Engine Initialized ");
  LOG_INFO("==================================================");
}
References LOG_INFO, and pdContext_.
Referenced by operator=(), and SolverEngine().
~SolverEngine()
GRPD::Engine::SolverEngine::~SolverEngine () [default]
SolverEngine() [2/2]
GRPD::Engine::SolverEngine::SolverEngine (const SolverEngine &) [delete]
References SolverEngine().
Member Function Documentation
InitConditionsPD()
void GRPD::Engine::SolverEngine::InitConditionsPD () [private]
Definition at line 18 of file SE_Condition.cpp.
                                    {
  auto &ctx = this->pdContext_;
  LOG_INFO("Entering Conditions Initialization Phase...");
  // =================================================================
  // 1. 解析 YAML 配置
  // =================================================================
  std::string yamlPath = "../../Input/PD.yaml";
  YAML::Node config;
  try {
    config = YAML::LoadFile(yamlPath);
  } catch (const YAML::BadFile &e) {
    LOG_ERROR("Failed to load YAML file in InitConditionsPD: " +
              std::string(e.what()));
    exit(EXIT_FAILURE);
  }
  // =================================================================
  // 2. 从 .grpd 文件的 *LOAD 段读取载荷并施加到物理场
  // =================================================================
  std::string grpdPath = "";
  if (config["Assembly"] && config["Assembly"]["OutputGrpd"]) {
    grpdPath = config["Assembly"]["OutputGrpd"].as<std::string>();
  } else {
    LOG_ERROR("[InitConditions] Key [Assembly][OutputGrpd] not found! "
              "Cannot read load data.");
    return;
  }
  LOG_INFO("[InitConditions] Reading load data from .grpd file: " + grpdPath);
  if (!GRPD::IO::GrpdReader::readLoads(grpdPath, ctx)) {
    LOG_ERROR("[InitConditions] Failed to read loads from .grpd file!");
    return;
  }
  LOG_INFO("[InitConditions] Boundary conditions initialization complete.");
}
References LOG_ERROR, LOG_INFO, pdContext_, and GRPD::IO::GrpdReader::readLoads().
Referenced by Initialize().
InitFieldsPD()
void GRPD::Engine::SolverEngine::InitFieldsPD () [private]
Definition at line 19 of file SE_Field.cpp.
                                {
  auto &ctx = this->pdContext_;
  LOG_INFO("Entering Field Registration Phase...");
  // =================================================================
  // 1. 解析 YAML 配置，获取 Solver.Type
  // =================================================================
  std::string yamlPath = "../../Input/PD.yaml";
  YAML::Node config;
  try {
    config = YAML::LoadFile(yamlPath);
  } catch (const YAML::BadFile &e) {
    LOG_ERROR("Failed to load YAML file in InitFieldsPD: " +
              std::string(e.what()));
    exit(EXIT_FAILURE);
  }
  std::string solverType = "";
  if (config["Solver"] && config["Solver"]["Type"]) {
    solverType = config["Solver"]["Type"].as<std::string>();
  }
  auto &fieldManager = ctx.getFieldManager();
  // =================================================================
  // 2. 解析 Solver.Type，通过 PhysicsFieldRegistry 多态注册核心场
  // 支持组合类型（如 "ThermalMechanical" 同时激活热场和力学场）
  // =================================================================
  auto &registry = GRPD::Field::PhysicsFieldRegistry::getInstance();
  // 检查已注册的物理类型，逐一匹配
  bool anyMatch = false;
  if (solverType.find("Thermal") != std::string::npos &&
      registry.hasType("Thermal")) {
    auto thermalFields = registry.create("Thermal");
    thermalFields->registerFields(fieldManager);
    anyMatch = true;
  }
  if (solverType.find("Mechanical") != std::string::npos &&
      registry.hasType("Mechanical")) {
    auto mechFields = registry.create("Mechanical");
    mechFields->registerFields(fieldManager);
    anyMatch = true;
  }
  if (!anyMatch) {
    LOG_WARNING("[InitFields] Solver type '" + solverType +
                "' did not match any registered PhysicsFields types.");
  }
  // =================================================================
  // 3. 遍历所有材料，让每个材料子类注册其私有的状态变量场
  // （材料驱动，完全解耦，对标 ABAQUS SDV 机制）
  // =================================================================
  auto &matManager = ctx.getMaterialManager();
  for (const auto &[matName, matPtr] : matManager.getMaterials()) {
    if (matPtr) {
      matPtr->allocateStateVariables(fieldManager);
    }
  }
  // =================================================================
  // 4. 统一为所有已注册场分配内存
  // =================================================================
  size_t numParticles = ctx.getParticleManager().getTotalParticles();
  fieldManager.resizeAll(numParticles);
  LOG_INFO("[InitFields] All fields allocated for " +
           std::to_string(numParticles) + " particles. Total fields: " +
           std::to_string(fieldManager.getFieldCount()) + ".");
}
References GRPD::Field::PhysicsFieldRegistry::getInstance(), LOG_ERROR, LOG_INFO, LOG_WARNING, and pdContext_.
Referenced by Initialize().
Initialize()
void GRPD::Engine::SolverEngine::Initialize (const std::string & yamlPath = "../../Input/PD.yaml")
初始化整个仿真工程（解析参数、生成网格、分配材料等）
Definition at line 17 of file SolverEngine.cpp.
                                                       {
  LOG_INFO("Entering Pre-processing Phase (Model & Material Initialization)");
  // 1. 调用底层函数生成/读取包含粒子和几何信息的纯数据上下文
  this->InitModelPD();
  // 2. 初始化材料
  this->InitMaterialPD();
  // 3. 注册物理场与材料状态变量
  this->InitFieldsPD();
  // 4. 初始化边界条件与载荷
  this->InitConditionsPD();
  LOG_INFO("PD Simulation context successfully initialized.");
}
References InitConditionsPD(), InitFieldsPD(), InitMaterialPD(), InitModelPD(), and LOG_INFO.
Referenced by main().
InitMaterialPD()
void GRPD::Engine::SolverEngine::InitMaterialPD () [private]
Definition at line 16 of file SE_Material.cpp.
                                  {
  auto &ctx = this->pdContext_;
  LOG_INFO("Entering Material Initialization Phase...");
  std::string yamlPath = "../../Input/PD.yaml";
  YAML::Node config;
  try {
    config = YAML::LoadFile(yamlPath);
  } catch (const YAML::BadFile &e) {
    LOG_ERROR("Failed to load YAML file in InitMaterialPD: " +
              std::string(e.what()));
    exit(EXIT_FAILURE);
  }
  // 1. Create Materials and add to Manager
  auto &matManager = ctx.getMaterialManager();
  std::unordered_map<int, GRPD::Material::Material *> idToMatMap;
  // 获取材料配置节点 (支持单数 Material 或 复数 Materials)
  YAML::Node materialsNode;
  if (config["Materials"]) {
    materialsNode = config["Materials"];
  } else if (config["Material"]) {
    materialsNode = config["Material"];
  }
  if (materialsNode) {
    // 统一转换为列表处理：如果不是序列，就包装成只含一个元素的序列
    std::vector<YAML::Node> nodes;
    if (materialsNode.IsSequence()) {
      for (const auto &n : materialsNode) {
        nodes.push_back(n);
      }
    } else {
      nodes.push_back(materialsNode);
    }
    // 循环实例化所有定义的材料
    for (const auto &matNode : nodes) {
      try {
        int matId = matNode["MatID"] ? matNode["MatID"].as<int>() : 1;
        std::string type = matNode["Type"].as<std::string>();
        std::string name =
            matNode["Name"] ? matNode["Name"].as<std::string>() : "";
        LOG_INFO("Instantiating material [" + std::to_string(matId) +
                 "] of type: " + type);
        std::string keyName =
            name.empty() ? "Mat_" + std::to_string(matId) : name;
        // 利用工厂模式创建实例
        auto matPtr =
            GRPD::Material::MaterialRegistry::getInstance().createMaterial(
                type, keyName);
        if (matPtr) {
          matPtr->initialize(matNode);
          matPtr->setName(keyName);
          matPtr->setMatId(matId);
          idToMatMap[matId] = matPtr.get();
          matManager.addMaterial(keyName, std::move(matPtr));
          LOG_INFO("Successfully registered material ID " +
                   std::to_string(matId) + " (" + keyName + ")");
        }
      } catch (const std::exception &e) {
        LOG_ERROR("Error parsing material entry: " + std::string(e.what()));
      }
    }
  } else {
    LOG_WARNING("No 'Material' or 'Materials' section found in PD.yaml!");
  }
  // 2. Assign Material Pointers to Particles
  LOG_INFO("Assigning material pointers to particles...");
  auto &particleArray = ctx.getParticleManager().getAllParticles();
  int assignCount = 0;
  for (auto &p : particleArray) {
    int matId = p.getMatId();
    GRPD::Material::Material *assignedMat = nullptr;
    auto it = idToMatMap.find(matId);
    if (it != idToMatMap.end()) {
      assignedMat = it->second;
    }
    if (assignedMat) {
      p.setMaterial(assignedMat);
      assignCount++;
    } else {
      LOG_ERROR("Particle ID " + std::to_string(p.getId()) +
                " requests MatID " + std::to_string(matId) +
                " but it was not defined in YAML!");
    }
  }
  LOG_INFO("Successfully assigned materials to " + std::to_string(assignCount) +
           " particles.");
}
References GRPD::Material::MaterialRegistry::createMaterial(), GRPD::Material::MaterialRegistry::getInstance(), LOG_ERROR, LOG_INFO, LOG_WARNING, and pdContext_.
Referenced by Initialize().
InitModelPD()
void GRPD::Engine::SolverEngine::InitModelPD () [private]
Definition at line 17 of file SE_Model.cpp.
                               {
  auto &ctx = this->pdContext_;
  // =================================================================
  // Generate the initial mesh and save it to a .grpd file
  // =================================================================
  LOG_INFO("Model pre-processing...");
  LOG_INFO("Calling Python pre-processor to generate .grpd mesh...");
  std::string pythonCommand =
      "python ../../Input/generate_model.py ../../Input/PD.yaml";
  // Execute the command via std::system and capture the return value
  int pyStatus = std::system(pythonCommand.c_str());
  // Check if the Python script executed successfully (0 means success)
  if (pyStatus != 0) {
    LOG_ERROR("Python pre-processor failed! Please check if python is "
              "installed and paths are correct.");
    LOG_ERROR("Exit code: " + std::to_string(pyStatus));
    exit(EXIT_FAILURE); // Terminate the program immediately
  }
  LOG_INFO("Mesh generated successfully by Python.");
  // =================================================================
  // Parse YAML to get OutputGrpd path and derive model name
  // =================================================================
  LOG_INFO("Parsing PD.yaml to extract model configuration...");
  std::string yamlPath = "../../Input/PD.yaml";
  std::string grpdPath = "";
  std::string currentModelName = "";
  try {
    YAML::Node config = YAML::LoadFile(yamlPath);
    // 1. 采用版本 B 的高防御力：精准检查节点是否存在
    if (config["Assembly"] && config["Assembly"]["OutputGrpd"]) {
      grpdPath = config["Assembly"]["OutputGrpd"].as<std::string>();
      // 2. 采用版本 A 的极简优雅：使用 C++17 filesystem 提取文件名
      std::filesystem::path p(grpdPath);
      currentModelName = p.stem().string();
    } else {
      LOG_ERROR("Key [Assembly][OutputGrpd] not found in YAML file!");
      exit(EXIT_FAILURE);
    }
  } catch (const YAML::Exception &e) {
    LOG_ERROR("Failed to parse YAML file: " + std::string(e.what()));
    exit(EXIT_FAILURE);
  }
  // =================================================================
  // Define current model context (Replacing global registry with instance)
  // =================================================================
  ctx.setName(currentModelName);
  LOG_INFO(std::string("[Context Manager] Formalized model name to: ") +
           ctx.getName());
  auto &manager = ctx.getParticleManager();
  // =================================================================
  // Read .grpd file and populate the specific particle manager
  // =================================================================
  LOG_INFO("Reading .grpd model file: " + grpdPath + " ...");
  if (!GRPD::IO::GrpdReader::read(grpdPath, manager)) {
    LOG_ERROR("Failed to read .grpd file!");
    exit(EXIT_FAILURE);
  }
  // =================================================================
  // Read done and print the total number of particles
  // =================================================================
  LOG_INFO("Total particles loaded for model " + currentModelName + ": " +
           std::to_string(manager.getTotalParticles()));
  // =================================================================
  // Verification: print info for the first 5 particles
  // =================================================================
  size_t previewCount =
      std::min(static_cast<size_t>(5), manager.getTotalParticles());
  for (size_t i = 0; i < previewCount; i++) {
    const auto &p = manager.getParticle(static_cast<int>(i));
    LOG_INFO(" Particle[" + std::to_string(p.getId()) +
             "] Part=" + std::to_string(p.getPartId()) + " Pos=(" +
             std::to_string(p.getCoords()[0]) + ", " +
             std::to_string(p.getCoords()[1]) + ", " +
             std::to_string(p.getCoords()[2]) + ")" +
             " Vol=" + std::to_string(p.getVolume()));
  }
}
References LOG_ERROR, LOG_INFO, pdContext_, and GRPD::IO::GrpdReader::read().
Referenced by Initialize().
operator=()
SolverEngine & GRPD::Engine::SolverEngine::operator= (const SolverEngine &) [delete]
References SolverEngine().
Output()
void GRPD::Engine::SolverEngine::Output ()
将当前步的结果导出到文件
Definition at line 44 of file SolverEngine.cpp.
                          {
  LOG_INFO("Entering Post-processing Phase (Exporting Data)");
  // 将物理宇宙的数据传到底层 IO 模块写出
  this->OutputPD();
}
References LOG_INFO, and OutputPD().
Referenced by main().
OutputPD()
void GRPD::Engine::SolverEngine::OutputPD () [private]
Definition at line 18 of file SE_Output.cpp.
                            {
  const auto &currentModel = this->pdContext_;
  LOG_INFO("Starting data export process...");
  // =================================================================
  // 1. Parse YAML to find the current model context name
  // =================================================================
  std::string yamlPath = "../../Input/PD.yaml";
  std::string grpdPath = "";
  std::string currentModelName = currentModel.getName();
  GRPD::IO::fileFormat format = GRPD::IO::ascii; // default to ascii
  std::string customWriterName = "";
  std::vector<std::pair<std::string, int>>
      variablesToOutput; // {Name, Dimension}
  try {
    YAML::Node config = YAML::LoadFile(yamlPath);
    if (config["Assembly"] && config["Assembly"]["OutputGrpd"]) {
      // We already have the model name from the passed object
    } else {
      LOG_ERROR("Key [Assembly][OutputGrpd] not found in YAML file!");
      return;
    }
    if (config["Writer"]) {
      if (config["Writer"]["Name"]) {
        customWriterName = config["Writer"]["Name"].as<std::string>();
      }
      if (config["Writer"]["Type"]) {
        std::string typeStr = config["Writer"]["Type"].as<std::string>();
        if (typeStr == "BINARY" || typeStr == "binary") {
          format = GRPD::IO::binary;
        } else if (typeStr == "ASCII" || typeStr == "ascii") {
          format = GRPD::IO::ascii;
        } else {
          LOG_INFO("Unknown Writer Type: " + typeStr +
                   ". Using default ASCII.");
        }
      }
      if (config["Writer"]["Variables"]) {
        for (auto it : config["Writer"]["Variables"]) {
          std::string varName = it["Name"].as<std::string>();
          int varDim = it["Dimension"] ? it["Dimension"].as<int>() : 1;
          variablesToOutput.push_back({varName, varDim});
        }
      } else {
        variablesToOutput.push_back({"Coords", 3});
        variablesToOutput.push_back({"PartID", 1});
        variablesToOutput.push_back({"Volume", 1});
      }
    }
  } catch (const YAML::Exception &e) {
    LOG_ERROR("Failed to parse YAML file in Write(): " + std::string(e.what()));
    return;
  }
  // =================================================================
  // 2. Fetch the corresponding ParticleManager from model context
  // =================================================================
  LOG_INFO("Fetching model context for export: " + currentModelName);
  try {
    const auto &manager = currentModel.getParticleManager();
    const auto &fieldManager = currentModel.getFieldManager();
    // =================================================================
    // 3. Export data using VtkWriter
    // =================================================================
    std::string finalOutputName =
        customWriterName.empty() ? currentModelName : customWriterName;
    std::string vtkOutputPath =
        "../../Output/" + finalOutputName + "_output.vtk";
    LOG_INFO("Exporting to VTK format: " + vtkOutputPath);
    int numParticles = static_cast<int>(manager.getTotalParticles());
    if (numParticles == 0) {
      LOG_INFO("No particles to export for model: " + currentModelName);
      return;
    }
    GRPD::IO::VtkWriter writer(vtkOutputPath, numParticles, format);
    // Set points geometry
    double *coordsPtr = manager.getGeomDataPtr(GRPD::Model::ModelVar::Coords);
    if (coordsPtr) {
      writer.setPointsInfo(GRPD::IO::Float64, coordsPtr, "Coordinates", 3);
    } else {
      LOG_ERROR("Failed to extract Coordinates. Aborting write.");
      return;
    }
    // Set physical variables dynamically based on user config
    for (const auto &[varName, yamlDim] : variablesToOutput) {
      if (varName == "Coords") {
        continue; // Coordinates are handled separately above
      }
      // ---------------------------------------------------------------
      // 优先从 FieldManager 查询物理场变量
      // FieldManager 统一存储所有物理场（Temperature, HeatFlux 等）
      // ---------------------------------------------------------------
      if (fieldManager.hasField(varName)) {
        const auto *field = fieldManager.getField(varName);
        if (field && field->rawPtr()) {
          writer.setPointsVariable(GRPD::IO::Float64,
                                   const_cast<double *>(field->rawPtr()),
                                   varName.c_str(), yamlDim);
          LOG_INFO("Exported field '" + varName + "' from FieldManager.");
        } else {
          LOG_WARNING("Field '" + varName + "' data pointer is null. Skipping.");
        }
        continue;
      }
      // ---------------------------------------------------------------
      // 通用路由：来自 ParticleManager 的几何/拓扑变量
      // ---------------------------------------------------------------
      GRPD::Model::ModelVar enumName;
      GRPD::Model::ParticleManager::VarDataType dataType;
      int managerDim = 1;
      if (GRPD::Model::ParticleManager::getModelVarInfo(varName, enumName,
                                                        dataType, managerDim)) {
        void *dataPtr = nullptr;
        GRPD::IO::dataType vtkType = GRPD::IO::Float64;
        // Fetch the corresponding data pointer based on its specific type
        if (dataType == GRPD::Model::ParticleManager::VarDataType::Double) {
          dataPtr = manager.getGeomDataPtr(enumName);
          vtkType = GRPD::IO::Float64;
        } else if (dataType == GRPD::Model::ParticleManager::VarDataType::Int) {
          dataPtr = manager.getIntDataPtr(enumName);
          vtkType = GRPD::IO::Int32;
        }
        // Use the dimension specified in YAML configuration
        int finalDim = yamlDim;
        // If pointer extraction was successful, pass it to VTK Writer
        if (dataPtr) {
          writer.setPointsVariable(vtkType, dataPtr, varName.c_str(), finalDim);
        } else {
          LOG_WARNING("Data array for " + varName +
                      " is empty or null. Skipping.");
        }
      } else {
        LOG_WARNING("Unknown output variable requested: " + varName +
                    ". Skipping.");
      }
    }
    // =================================================================
    // 4. Execute writing
    // =================================================================
    writer.write();
    LOG_INFO("Successfully exported data for model: " + currentModelName);
  } catch (const std::exception &e) {
    LOG_ERROR("Write process aborted: " + std::string(e.what()));
  }
}
References GRPD::IO::ascii, GRPD::IO::binary, GRPD::Model::Coords, GRPD::Model::ParticleManager::Double, GRPD::IO::Float64, GRPD::Model::ParticleManager::getModelVarInfo(), GRPD::Model::ParticleManager::Int, GRPD::IO::Int32, LOG_ERROR, LOG_INFO, LOG_WARNING, pdContext_, GRPD::IO::Writer::setPointsInfo(), GRPD::IO::Writer::setPointsVariable(), and GRPD::IO::VtkWriter::write().
Referenced by Output(), and SolvePD().
Solve()
void GRPD::Engine::SolverEngine::Solve ()
启动主求解循环
Definition at line 35 of file SolverEngine.cpp.
                         {
  LOG_INFO("Entering Main Solver Phase");
  // 执行计算循环
  this->SolvePD();
  LOG_INFO("Main Solver Phase finished.");
}
References LOG_INFO, and SolvePD().
SolvePD()
void GRPD::Engine::SolverEngine::SolvePD () [private]
Definition at line 17 of file SE_Solve.cpp.
                           {
  auto &ctx = this->pdContext_;
  LOG_INFO("Starting PD Solver Loop...");
  // =================================================================
  // 1. 获取仿真参数 (从 YAML)
  // =================================================================
  std::string yamlPath = "../../Input/PD.yaml";
  YAML::Node config = YAML::LoadFile(yamlPath);
  double dt = 1e-4;
  double totalTime = 1.0;
  int outputInterval = 10;
  if (config["Solver"]) {
    if (config["Solver"]["TimeStep_dt"])
      dt = config["Solver"]["TimeStep_dt"].as<double>();
    if (config["Solver"]["TotalTime"])
      totalTime = config["Solver"]["TotalTime"].as<double>();
    if (config["Solver"]["OutputInterval"])
      outputInterval = config["Solver"]["OutputInterval"].as<int>();
  }
  int totalSteps = static_cast<int>(totalTime / dt);
  // =================================================================
  // 2. 获取物理场指针（从 FieldManager）
  // =================================================================
  auto &fieldManager = ctx.getFieldManager();
  if (!fieldManager.hasField("Temperature")) {
    LOG_ERROR("No Temperature field found! Aborting solver.");
    return;
  }
  auto *tempField = fieldManager.getFieldAs<double>("Temperature");
  auto *rateField = fieldManager.getFieldAs<double>("TempRate");
  auto *fluxField = fieldManager.getFieldAs<double>("HeatFlux");
  auto &neighborList = ctx.getNeighborList();
  auto &manager = ctx.getParticleManager();
  auto &bcManager = ctx.getBCManager();
  size_t numParticles = manager.getTotalParticles();
  double horizon = neighborList.getHorizon();
  // 3D 微导率系数 (Bobaru model): kappa = 6k / (pi * delta^4)
  // 注意：每个点的材料可能不同，需要在循环内获取 k
  double PI = 3.14159265358979323846;
  double horizon4 = std::pow(horizon, 4.0);
  // 获取数据指针 (SoA)
  const double *volumes = manager.getGeomDataPtr(GRPD::Model::ModelVar::Volume);
  const double *coords = manager.getGeomDataPtr(GRPD::Model::ModelVar::Coords);
  // 获取 Field 的裸指针（用于 OpenMP 高性能循环）
  double *tempPtr = tempField->dataPtr();
  double *ratePtr = rateField->dataPtr();
  double *fluxPtr = fluxField->dataPtr();
  LOG_INFO("Time loop: Dt = " + std::to_string(dt) +
           ", TotalSteps = " + std::to_string(totalSteps));
  // =================================================================
  // 3. 时间步循环
  // =================================================================
  for (int step = 0; step <= totalSteps; ++step) {
    // (A) 输出结果
    if (step % outputInterval == 0) {
      LOG_INFO("--- Outputting Step: " + std::to_string(step));
      this->OutputPD();
    }
    if (step == totalSteps)
      break;
    // (B) 清零变化率
    rateField->clearToZero();
    fluxField->clearToZero();
    // (C) 施加所有边界条件中的源项 (含热流、对流)
    // 源项会累加至 TempRate 和 HeatFlux
    bcManager.applySources();
    
    // (C2) 施加强制约束 (Dirichlet) - 第一次施加用于更新初值
    bcManager.applyConstraints();
// (D) 计算 PD 键相互作用 (并行的热传导内核)
#pragma omp parallel for schedule(dynamic, 64)
    for (int i = 0; i < static_cast<int>(numParticles); ++i) {
      const auto &neighbors = neighborList.getNeighbors(i);
      if (neighbors.empty())
        continue;
      // 获取当前粒子材料属性
      auto *mat = dynamic_cast<GRPD::Material::ThermalMat *>(
          manager.getParticle(i).getMaterial());
      if (!mat)
        continue;
      double k = mat->getConductivity();
      double kappa_base = (6.0 * k) / (PI * horizon4);
      double Ti = tempPtr[i];
      const double *pos_i = &coords[3 * i];
      double totalContribution = 0.0;
      for (int j : neighbors) {
        double Tj = tempPtr[j];
        const double *pos_j = &coords[3 * j];
        double dx = pos_j[0] - pos_i[0];
        double dy = pos_j[1] - pos_i[1];
        double dz = pos_j[2] - pos_i[2];
        double dist = std::sqrt(dx * dx + dy * dy + dz * dz);
        if (dist < 1e-12)
          continue; // 避免自耦合或重合点
        // PD 传导公式：kappa * (Tj - Ti) / dist * Vj
        // 注意：有些公式是 / dist^2，这里按 Bobaru (2012)
        // 积分项为 \int kappa * (Tj - Ti)/dist dVj
        double bondContribution = kappa_base * ((Tj - Ti) / dist) * volumes[j];
        totalContribution += bondContribution;
      }
      rateField->add(i, totalContribution);
      fluxField->add(i, totalContribution);
    }
// (E) 显式时间积分：T_new = T_old + (Rate / (rho * Cp)) * dt
#pragma omp parallel for
    for (int i = 0; i < static_cast<int>(numParticles); ++i) {
      auto *mat = dynamic_cast<GRPD::Material::ThermalMat *>(
          manager.getParticle(i).getMaterial());
      if (!mat)
        continue;
      double rho = mat->getDensity();
      double cp = mat->getHeatCapacity();
      // 注意：bcManager 施加的 Flux 是 Q (功率)，
      // PD Kernel 计算出的也是源项率
      // dT/dt = Net_Rate / (rho * Cp)
      double heatRate = ratePtr[i];
      double deltaT = (heatRate / (rho * cp)) * dt;
      tempPtr[i] += deltaT;
    }
    // (F) 施加固定温度约束 (Dirichlet) - 时间积分后重新强制覆盖
    bcManager.applyConstraints();
  }
  LOG_INFO("PD Solver Simulation Finished.");
}
References GRPD::Model::Coords, GRPD::Material::ThermalMat::getConductivity(), GRPD::Material::ThermalMat::getDensity(), LOG_ERROR, LOG_INFO, OutputPD(), pdContext_, and GRPD::Model::Volume.
Referenced by Solve().
Member Data Documentation
pdContext_
GRPD::Core::PDSimulater GRPD::Engine::SolverEngine::pdContext_ [private]
Definition at line 51 of file SolverEngine.h.
Referenced by InitConditionsPD(), InitFieldsPD(), InitMaterialPD(), InitModelPD(), OutputPD(), SolvePD(), and SolverEngine().
The documentation for this class was generated from the following files:
Src/Engine/include/SolverEngine.h
Src/Engine/src/SE_Condition.cpp
Src/Engine/src/SE_Field.cpp
Src/Engine/src/SE_Material.cpp
Src/Engine/src/SE_Model.cpp
Src/Engine/src/SE_Output.cpp
Src/Engine/src/SE_Solve.cpp
Src/Engine/src/SolverEngine.cpp