GRPD::Field::PhysicsFieldRegistry Class Reference
#include <PhysicsFieldRegistry.h>
Public Member Functions
PhysicsFieldRegistry (const PhysicsFieldRegistry &)=delete
PhysicsFieldRegistry & operator= (const PhysicsFieldRegistry &)=delete
void registerType (const std::string &type, PhysicsFieldsCreatorFunc creator)
注册物理场配置器类型
std::unique_ptr< PhysicsFields > create (const std::string &type)
创建物理场配置器实例
bool hasType (const std::string &type) const
检查是否已注册某类型
Static Public Member Functions
static PhysicsFieldRegistry & getInstance ()
获取单例
Private Member Functions
PhysicsFieldRegistry ()=default
~PhysicsFieldRegistry ()=default
Private Attributes
std::map< std::string, PhysicsFieldsCreatorFunc > registry_
Detailed Description
Definition at line 22 of file PhysicsFieldRegistry.h.
Constructor & Destructor Documentation
PhysicsFieldRegistry() [1/2]
GRPD::Field::PhysicsFieldRegistry::PhysicsFieldRegistry (const PhysicsFieldRegistry &) [delete]
References PhysicsFieldRegistry().
Referenced by getInstance(), operator=(), and PhysicsFieldRegistry().
PhysicsFieldRegistry() [2/2]
GRPD::Field::PhysicsFieldRegistry::PhysicsFieldRegistry () [private], [default]
~PhysicsFieldRegistry()
GRPD::Field::PhysicsFieldRegistry::~PhysicsFieldRegistry () [private], [default]
Member Function Documentation
create()
std::unique_ptr< PhysicsFields > GRPD::Field::PhysicsFieldRegistry::create (const std::string & type)
创建物理场配置器实例
Parameters
type 已注册的类型名
Returns
配置器实例的 unique_ptr
Definition at line 28 of file PhysicsFieldRegistry.cpp.
                                                  {
    auto it = registry_.find(type);
    if (it == registry_.end()) {
        LOG_ERROR("[PhysicsFieldRegistry] Unknown physics type: '" + type +
                  "'!");
        throw std::runtime_error("Unknown PhysicsFields type: " + type);
    }
    return it->second();
}
References LOG_ERROR, and registry_.
getInstance()
PhysicsFieldRegistry & GRPD::Field::PhysicsFieldRegistry::getInstance () [static]
获取单例
Definition at line 11 of file PhysicsFieldRegistry.cpp.
                                                        {
    static PhysicsFieldRegistry instance;
    return instance;
}
References PhysicsFieldRegistry().
Referenced by GRPD::Engine::SolverEngine::InitFieldsPD().
hasType()
bool GRPD::Field::PhysicsFieldRegistry::hasType (const std::string & type) const
检查是否已注册某类型
Definition at line 38 of file PhysicsFieldRegistry.cpp.
                                                              {
    return registry_.find(type) != registry_.end();
}
References registry_.
operator=()
PhysicsFieldRegistry & GRPD::Field::PhysicsFieldRegistry::operator= (const PhysicsFieldRegistry &) [delete]
References PhysicsFieldRegistry().
registerType()
void GRPD::Field::PhysicsFieldRegistry::registerType (const std::string & type, PhysicsFieldsCreatorFunc creator)
注册物理场配置器类型
Parameters
type 类型名（如 "Thermal", "Mechanical"）
creator 工厂函数
Definition at line 16 of file PhysicsFieldRegistry.cpp.
                                                                           {
    if (registry_.find(type) != registry_.end()) {
        LOG_WARNING("[PhysicsFieldRegistry] Type '" + type +
                    "' already registered, overwriting.");
    } else {
        LOG_INFO("[PhysicsFieldRegistry] Type '" + type + "' registered.");
    }
    registry_[type] = creator;
}
References LOG_INFO, LOG_WARNING, and registry_.
Member Data Documentation
registry_
std::map<std::string, PhysicsFieldsCreatorFunc> GRPD::Field::PhysicsFieldRegistry::registry_ [private]
Definition at line 48 of file PhysicsFieldRegistry.h.
Referenced by create(), hasType(), and registerType().
The documentation for this class was generated from the following files:
PDCommon/Field/include/PhysicsFieldRegistry.h
PDCommon/Field/src/PhysicsFieldRegistry.cpp