PDCommon::Utils::Logger Class Reference
Global logger manager (Singleton pattern) Handles all log output (console and file) and Logo display. Thread-safe for OpenMP multi-threading.
#include <Logger.h>
Public Member Functions
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
void setLogFile (const std::string &logFilePath)
void showLogo ()
void info (const std::string &message)
void warning (const std::string &message)
void error (const std::string &message)
Static Public Member Functions
static Logger & getInstance ()
Private Member Functions
Logger ()=default
~Logger ()
std::vector< std::string > buildLogoLines ()
void printToStreams (const std::vector< std::string > &lines)
Private Attributes
std::mutex logMutex_
std::ofstream logFile_
Detailed Description
Global logger manager (Singleton pattern) Handles all log output (console and file) and Logo display. Thread-safe for OpenMP multi-threading.
Definition at line 22 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
PDCommon::Utils::Logger::Logger (const Logger &) [delete]
References Logger().
Referenced by getInstance(), Logger(), and operator=().
Logger() [2/2]
PDCommon::Utils::Logger::Logger () [private], [default]
~Logger()
PDCommon::Utils::Logger::~Logger () [private]
Definition at line 17 of file Logger.cpp.
                {
  if (logFile_.is_open()) {
    logFile_.close();
  }
}
References logFile_.
Member Function Documentation
buildLogoLines()
std::vector< std::string > PDCommon::Utils::Logger::buildLogoLines () [private]
Definition at line 38 of file Logger.cpp.
                                            {
  std::vector<std::string> lines;
  // ====== Logo 1: GRPD ======
  lines.push_back(
      "*****************************************************************");
  lines.push_back(
      " ____ ____ ____ ____ ");
  lines.push_back(
      " / ___|| _ \\ | _ \\ | _ \\ ");
  lines.push_back(
      " | | _ | |_) || |_) || | | | ");
  lines.push_back(
      " | |_| || _ < | __/ | |_| | v1.0 ");
  lines.push_back(
      " \\____||_| \\_\\|_| |____/ ");
  lines.push_back(
      "*****************************************************************");
  lines.push_back("");
  // ====== Logo 2: GRPD (Block Style) ======
  lines.push_back(
      "*****************************************************************");
  lines.push_back(
      " #### #### #### #### ");
  lines.push_back(
      " ## ## ## ## ## ## ## ## ");
  lines.push_back(
      " ## ## ## ## # ## ## ");
  lines.push_back(
      " ## ### ##### #### ## ## ");
  lines.push_back(
      " ## ## ## ## ## ## ## ");
  lines.push_back(
      " ## ## ## ## ## ## ## ");
  lines.push_back(
      " #### ## ## ## #### ");
  lines.push_back(
      "*****************************************************************");
  lines.push_back("");
  // ====== Logo 3: Pipe Style GrPD ======
  lines.push_back(" _____ _____ "
                  "_____ _____ ");
  lines.push_back(" /\\ \\ /\\ \\ "
                  " /\\ \\ /\\ \\ ");
  lines.push_back(" /::\\ \\ /::\\ \\ "
                  " /::\\ \\ /::\\ \\ ");
  lines.push_back(" /::::\\ \\ /::::\\ \\ "
                  " /::::\\ \\ /::::\\ \\ ");
  lines.push_back(" /::::::\\ \\ /::::::\\ \\ "
                  "/::::::\\ \\ /::::::\\ \\ ");
  lines.push_back(" /:::/\\:::\\ \\ /:::/\\:::\\ \\ "
                  " /:::/\\:::\\ \\ /:::/\\:::\\ \\ ");
  lines.push_back(" /:::/ \\:::\\ \\ /:::/__\\:::\\ \\ "
                  "/:::/__\\:::\\ \\ /:::/ \\:::\\ \\ ");
  lines.push_back(" /:::/ \\:::\\ \\ /::::\\ \\:::\\ \\ "
                  "/::::\\ \\:::\\ \\ /:::/ \\:::\\ \\ ");
  lines.push_back(" /:::/ / \\:::\\ \\ /::::::\\ \\:::\\ \\ "
                  "/::::::\\ \\:::\\ \\ /:::/ / \\:::\\ \\ ");
  lines.push_back(" /:::/ / \\:::\\ ___\\ /:::/\\:::\\ \\:::\\____\\ "
                  "/:::/\\:::\\ \\:::\\____\\ /:::/ / \\:::\\ ___\\ ");
  lines.push_back("/:::/____/ ___\\:::| |/:::/ \\:::\\ \\:::| |/:::/ "
                  " \\:::\\ \\:::| |/:::/____/ \\:::| |");
  lines.push_back(
      "\\:::\\ \\ /\\ /:::|____|\\::/ |::::\\ /:::|____|\\::/ "
      "\\:::\\ /:::|____|\\:::\\ \\ /:::|____|");
  lines.push_back(" \\:::\\ /::\\ \\::/ / \\/____|:::::\\/:::/ / "
                  "\\/_____/\\:::\\/:::/ / \\:::\\ \\ /:::/ / ");
  lines.push_back(" \\:::\\ \\:::\\ \\/____/ |:::::::::/ / "
                  " \\::::::/ / \\:::\\ \\ /:::/ / ");
  lines.push_back(" \\:::\\ \\:::\\____\\ |::|\\::::/ / "
                  " \\::::/ / \\:::\\ /:::/ / ");
  lines.push_back(" \\:::\\ /:::/ / |::| \\::/____/ "
                  " \\::/____/ \\:::\\ /:::/ / ");
  lines.push_back(" \\:::\\/:::/ / |::| ~| "
                  " ~~ \\:::\\/:::/ / ");
  lines.push_back(" \\::::::/ / |::| | "
                  " \\::::::/ / ");
  lines.push_back(" \\::::/ / \\::| | "
                  " \\::::/ / ");
  lines.push_back(" \\::/____/ \\:| | "
                  " \\::/____/ ");
  lines.push_back(" \\|___| "
                  " ~~ ");
  lines.push_back("");
  // ====== Logo 4: Letter-based Pattern ======
  lines.push_back(
      "*****************************************************************");
  lines.push_back(" GGGGGGG RRRRRR PPPPPP DDDDD ");
  lines.push_back(" GG RR RR PP PP DD DD ");
  lines.push_back(" GG RR RR PP PP DD DD ");
  lines.push_back(" GG GGG RRRRRR PPPPPP DD DD ");
  lines.push_back(" GG GG RR RR PP DD DD ");
  lines.push_back(" GG GG RR RR PP DD DD ");
  lines.push_back(" GGGGGGG RR RR PP DDDDD ");
  lines.push_back(
      "*****************************************************************");
  lines.push_back("");
  return lines;
}
Referenced by showLogo().
error()
void PDCommon::Utils::Logger::error (const std::string & message)
Definition at line 184 of file Logger.cpp.
                                           {
  std::lock_guard<std::mutex> lock(logMutex_);
  std::string outMsg = "[ERROR] " + message;
  std::cerr << outMsg << std::endl;
  if (logFile_.is_open()) {
    logFile_ << outMsg << std::endl;
  }
}
References logFile_, and logMutex_.
getInstance()
Logger & PDCommon::Utils::Logger::getInstance () [static]
Definition at line 12 of file Logger.cpp.
                            {
  static Logger instance;
  return instance;
}
References Logger().
info()
void PDCommon::Utils::Logger::info (const std::string & message)
Definition at line 166 of file Logger.cpp.
                                          {
  std::lock_guard<std::mutex> lock(logMutex_);
  std::string outMsg = "[INFO] " + message;
  std::cout << outMsg << std::endl;
  if (logFile_.is_open()) {
    logFile_ << outMsg << std::endl;
  }
}
References logFile_, and logMutex_.
operator=()
Logger & PDCommon::Utils::Logger::operator= (const Logger &) [delete]
References Logger().
printToStreams()
void PDCommon::Utils::Logger::printToStreams (const std::vector< std::string > & lines) [private]
Definition at line 142 of file Logger.cpp.
                                                             {
  std::lock_guard<std::mutex> lock(logMutex_);
  // Use '\n' instead of endl for efficient line breaks inside loops, avoiding
  // frequent buffer flushes
  for (const auto &line : lines) {
    std::cout << line << "\n";
    if (logFile_.is_open()) {
      logFile_ << line << "\n";
    }
  }
  // Flush the buffer once after the loop completes
  std::cout << std::endl;
  if (logFile_.is_open()) {
    logFile_ << std::endl;
  }
}
References logFile_, and logMutex_.
Referenced by showLogo().
setLogFile()
void PDCommon::Utils::Logger::setLogFile (const std::string & logFilePath)
Definition at line 23 of file Logger.cpp.
                                                    {
  std::lock_guard<std::mutex> lock(logMutex_);
  if (logFile_.is_open()) {
    logFile_.close();
  }
  // Open file in append mode to ensure continuous logging across sessions
  logFile_.open(logFilePath, std::ios::app);
  if (!logFile_.is_open()) {
    std::cerr << "[WARNING] Failed to open log file: " << logFilePath
              << ", subsequent logs will only be output to the console."
              << std::endl;
  }
}
References logFile_, and logMutex_.
showLogo()
void PDCommon::Utils::Logger::showLogo ()
Definition at line 161 of file Logger.cpp.
                      {
  auto lines = buildLogoLines();
  printToStreams(lines);
}
References buildLogoLines(), and printToStreams().
warning()
void PDCommon::Utils::Logger::warning (const std::string & message)
Definition at line 175 of file Logger.cpp.
                                             {
  std::lock_guard<std::mutex> lock(logMutex_);
  std::string outMsg = "[WARNING] " + message;
  std::cout << outMsg << std::endl;
  if (logFile_.is_open()) {
    logFile_ << outMsg << std::endl;
  }
}
References logFile_, and logMutex_.
Member Data Documentation
logFile_
std::ofstream PDCommon::Utils::Logger::logFile_ [private]
Definition at line 54 of file Logger.h.
Referenced by error(), info(), printToStreams(), setLogFile(), warning(), and ~Logger().
logMutex_
std::mutex PDCommon::Utils::Logger::logMutex_ [private]
Definition at line 53 of file Logger.h.
Referenced by error(), info(), printToStreams(), setLogFile(), and warning().
The documentation for this class was generated from the following files:
PDCommon/Utils/include/Logger.h
PDCommon/Utils/src/Logger.cpp