GRPD::Model::ParticleManager Class Reference
#include <ParticleManager.h>
Public Types
enum class VarDataType { Int
, Double
 }
Public Member Functions
ParticleManager ()=default
void addParticle (int id, int partId, int matId, double x, double y, double z, double volume)
const Particle & getParticle (int id) const
O(1) indexed access - const version.
Particle & getParticle (int id)
O(1) indexed access - mutable version (e.g. for setting temperature)
size_t getTotalParticles () const
Get current total particle count.
void reserveMemory (size_t size)
const std::vector< Particle > & getAllParticles () const
Get const reference to the underlying array (for solver traversal)
std::vector< Particle > & getAllParticles ()
Get mutable reference to the underlying array (for solver field writes)
double * getGeomDataPtr (ModelVar varName) const
int * getIntDataPtr (ModelVar varName) const
Static Public Member Functions
static bool getModelVarInfo (const std::string &varName, ModelVar &outVar, VarDataType &outType, int &outDim)
Get the ModelVar enum and data type for a given variable string name.
Private Attributes
std::vector< Particle > globalParticles_
Detailed Description
Definition at line 21 of file ParticleManager.h.
Member Enumeration Documentation
VarDataType
enum class GRPD::Model::ParticleManager::VarDataType [strong]
Enumerator
Int
Double
Definition at line 63 of file ParticleManager.h.
{ Int, Double };
Constructor & Destructor Documentation
ParticleManager()
GRPD::Model::ParticleManager::ParticleManager () [default]
Member Function Documentation
addParticle()
void GRPD::Model::ParticleManager::addParticle (int id, int partId, int matId, double x, double y, double z, double volume)
Emplace-construct a new particle and push it into the global array
Parameters
id Globally unique ID (must equal current array size)
partId Part number this particle belongs to
matId Material ID assigned to this particle
x,y,z 3D coordinates
volume Particle volume
Definition at line 21 of file ParticleManager.cpp.
                                                                     {
  // Assert ID continuity: incoming id must exactly equal current array length
  if (static_cast<size_t>(id) != globalParticles_.size()) {
    LOG_ERROR("[ParticleManager] Error: particle ID=" + std::to_string(id) +
              " does not match expected index " +
              std::to_string(globalParticles_.size()) +
              "! Violates zero-based ID invariant!");
    throw std::runtime_error(
        "Particle ID does not match expected vector index.");
  }
  globalParticles_.emplace_back(id, partId, matId, x, y, z, volume);
}
References globalParticles_, and LOG_ERROR.
Referenced by GRPD::IO::GrpdReader::read().
getAllParticles() [1/2]
std::vector< Particle > & GRPD::Model::ParticleManager::getAllParticles ()
Get mutable reference to the underlying array (for solver field writes)
Definition at line 62 of file ParticleManager.cpp.
                                                      {
  return globalParticles_;
}
References globalParticles_.
getAllParticles() [2/2]
const std::vector< Particle > & GRPD::Model::ParticleManager::getAllParticles () const
Get const reference to the underlying array (for solver traversal)
Definition at line 58 of file ParticleManager.cpp.
                                                                  {
  return globalParticles_;
}
References globalParticles_.
getGeomDataPtr()
double * GRPD::Model::ParticleManager::getGeomDataPtr (ModelVar varName) const
Definition at line 69 of file ParticleManager.cpp.
                                                              {
  switch (varName) {
  case ModelVar::Coords:
    return Utils::DataExtractor::getVectorPtr<Particle, double, 3,
                                              &Particle::coords_>(
        globalParticles_);
  case ModelVar::Volume:
    return Utils::DataExtractor::getScalarPtr<Particle, double,
                                              &Particle::volume_>(
        globalParticles_);
  default:
    LOG_WARNING(
        "[ParticleManager] Requested unmapped double variable from ModelVar!");
    return nullptr;
  }
}
References GRPD::Model::Coords, GRPD::Model::Particle::coords_, GRPD::Utils::DataExtractor::getScalarPtr(), GRPD::Utils::DataExtractor::getVectorPtr(), globalParticles_, LOG_WARNING, GRPD::Model::Volume, and GRPD::Model::Particle::volume_.
getIntDataPtr()
int * GRPD::Model::ParticleManager::getIntDataPtr (ModelVar varName) const
Definition at line 87 of file ParticleManager.cpp.
                                                          {
  switch (varName) {
  case ModelVar::ID:
    return Utils::DataExtractor::getScalarPtr<Particle, int, &Particle::id_>(
        globalParticles_);
  case ModelVar::PartID:
    return Utils::DataExtractor::getScalarPtr<Particle, int,
                                              &Particle::partId_>(
        globalParticles_);
  case ModelVar::MatID:
    return Utils::DataExtractor::getScalarPtr<Particle, int, &Particle::matId_>(
        globalParticles_);
  default:
    LOG_WARNING(
        "[ParticleManager] Requested unmapped int variable from ModelVar!");
    return nullptr;
  }
}
References GRPD::Utils::DataExtractor::getScalarPtr(), globalParticles_, GRPD::Model::ID, LOG_WARNING, GRPD::Model::MatID, GRPD::Model::PartID, and GRPD::Model::Particle::partId_.
getModelVarInfo()
bool GRPD::Model::ParticleManager::getModelVarInfo (const std::string & varName, ModelVar & outVar, VarDataType & outType, int & outDim) [static]
Get the ModelVar enum and data type for a given variable string name.
Definition at line 106 of file ParticleManager.cpp.
                                                   {
  // Map structure: { "StringName", { ModelVarEnum, VarDataTypeEnum,
  // DimensionValue } }
  struct VarInfo {
    ModelVar var;
    VarDataType type;
    int dim;
  };
  static const std::unordered_map<std::string, VarInfo> varMap = {
      {"Coords", {ModelVar::Coords, VarDataType::Double, 3}},
      {"Volume", {ModelVar::Volume, VarDataType::Double, 1}},
      {"ID", {ModelVar::ID, VarDataType::Int, 1}},
      {"PartID", {ModelVar::PartID, VarDataType::Int, 1}},
      {"MatID", {ModelVar::MatID, VarDataType::Int, 1}}};
  auto it = varMap.find(varName);
  if (it != varMap.end()) {
    outVar = it->second.var;
    outType = it->second.type;
    outDim = it->second.dim;
    return true;
  }
  return false;
}
References GRPD::Model::Coords, Double, GRPD::Model::ID, Int, GRPD::Model::MatID, GRPD::Model::PartID, and GRPD::Model::Volume.
Referenced by GRPD::Engine::SolverEngine::OutputPD().
getParticle() [1/2]
Particle & GRPD::Model::ParticleManager::getParticle (int id)
O(1) indexed access - mutable version (e.g. for setting temperature)
Definition at line 52 of file ParticleManager.cpp.
{ return globalParticles_[id]; }
References globalParticles_.
getParticle() [2/2]
const Particle & GRPD::Model::ParticleManager::getParticle (int id) const
O(1) indexed access - const version.
Definition at line 48 of file ParticleManager.cpp.
                                                         {
  return globalParticles_[id];
}
References globalParticles_.
Referenced by GRPD::Initial::NeighborList::buildNeighbors().
getTotalParticles()
size_t GRPD::Model::ParticleManager::getTotalParticles () const
Get current total particle count.
Definition at line 54 of file ParticleManager.cpp.
                                                {
  return globalParticles_.size();
}
References globalParticles_.
Referenced by GRPD::Initial::NeighborList::buildNeighbors().
reserveMemory()
void GRPD::Model::ParticleManager::reserveMemory (size_t size)
Pre-allocate memory before file reading to avoid dynamic resizing jitter
Parameters
size Expected total particle count
Definition at line 39 of file ParticleManager.cpp.
                                               {
  globalParticles_.reserve(size);
  LOG_INFO("[ParticleManager] Pre-allocated memory for " +
           std::to_string(size) + " particles");
}
References globalParticles_, and LOG_INFO.
Member Data Documentation
globalParticles_
std::vector<Particle> GRPD::Model::ParticleManager::globalParticles_ [private]
Definition at line 70 of file ParticleManager.h.
Referenced by addParticle(), getAllParticles(), getAllParticles(), getGeomDataPtr(), getIntDataPtr(), getParticle(), getParticle(), getTotalParticles(), and reserveMemory().
The documentation for this class was generated from the following files:
PDCommon/Model/include/ParticleManager.h
PDCommon/Model/src/ParticleManager.cpp