GRPD::Utils::DataExtractor Class Reference
#include <DataExtractor.h>
Static Public Member Functions
template<typename C, typename T, T C::* MemberPtr>
static T * getScalarPtr (const std::vector< C > &container)
template<typename C, typename T, size_t N, std::array< T, N > C::* MemberPtr>
static T * getVectorPtr (const std::vector< C > &container)
Detailed Description
Definition at line 9 of file DataExtractor.h.
Member Function Documentation
getScalarPtr()
template<typename C, typename T, T C::* MemberPtr>
T * GRPD::Utils::DataExtractor::getScalarPtr (const std::vector< C > & container) [inline], [static]
Definition at line 14 of file DataExtractor.h.
                                                        {
    // Use thread_local to avoid repeated heavy allocations in the main thread
    thread_local std::vector<T> buf;
    buf.resize(container.size());
    for (size_t i = 0; i < container.size(); ++i) {
      buf[i] = container[i].*MemberPtr;
    }
    return buf.data();
  }
Referenced by GRPD::Model::ParticleManager::getGeomDataPtr(), and GRPD::Model::ParticleManager::getIntDataPtr().
getVectorPtr()
template<typename C, typename T, size_t N, std::array< T, N > C::* MemberPtr>
T * GRPD::Utils::DataExtractor::getVectorPtr (const std::vector< C > & container) [inline], [static]
Definition at line 27 of file DataExtractor.h.
                                                        {
    thread_local std::vector<T> buf;
    buf.resize(container.size() * N);
    for (size_t i = 0; i < container.size(); ++i) {
      const auto &arr = container[i].*MemberPtr;
      for (size_t j = 0; j < N; ++j) {
        buf[i * N + j] = arr[j];
      }
    }
    return buf.data();
  }
Referenced by GRPD::Model::ParticleManager::getGeomDataPtr().
The documentation for this class was generated from the following file:
PDCommon/Utils/include/DataExtractor.h