GRPD::Field::FieldManager Class Reference
#include <FieldManager.h>
Public Member Functions
FieldManager ()=default
~FieldManager ()=default
FieldManager (const FieldManager &)=delete
FieldManager & operator= (const FieldManager &)=delete
FieldManager (FieldManager &&)=default
FieldManager & operator= (FieldManager &&)=default
template<typename T = double>
TypedField< T > * registerField (const std::string &name, int dim=1)
注册一个新的物理场 如果同名场已存在，直接返回已有场的指针（幂等操作）
Field * getField (const std::string &name)
获取已注册的物理场基类指针（不存在返回 nullptr）
const Field * getField (const std::string &name) const
template<typename T = double>
TypedField< T > * getFieldAs (const std::string &name)
获取带类型安全的物理场指针（不存在或类型不匹配返回 nullptr）
bool hasField (const std::string &name) const
检查某个物理场是否已注册
std::vector< std::string > getFieldNames () const
获取所有已注册物理场的名称列表（用于调试/VTK 输出枚举）
size_t getFieldCount () const
获取已注册物理场总数
Field * createField (const std::string &typeName, const std::string &fieldName)
通过已注册的类型名创建物理场并加入管理器
void resizeAll (size_t numParticles)
对所有已注册的场统一按粒子数分配内存
Private Attributes
std::map< std::string, std::unique_ptr< Field > > fields_
物理场注册表：场名 -> unique_ptr<Field>
Detailed Description
Definition at line 21 of file FieldManager.h.
Constructor & Destructor Documentation
FieldManager() [1/3]
GRPD::Field::FieldManager::FieldManager () [default]
Referenced by FieldManager(), FieldManager(), operator=(), and operator=().
~FieldManager()
GRPD::Field::FieldManager::~FieldManager () [default]
FieldManager() [2/3]
GRPD::Field::FieldManager::FieldManager (const FieldManager &) [delete]
References FieldManager().
FieldManager() [3/3]
GRPD::Field::FieldManager::FieldManager (FieldManager &&) [default]
References FieldManager().
Member Function Documentation
createField()
Field * GRPD::Field::FieldManager::createField (const std::string & typeName, const std::string & fieldName)
通过已注册的类型名创建物理场并加入管理器
Parameters
typeName 已在 FieldRegistry 中注册的类型名（如 "ScalarField"）
fieldName 新场的实例名称（如 "Temperature", "Damage"）
Returns
新创建的 Field 指针（管理器持有所有权），失败返回 nullptr
Definition at line 42 of file FieldManager.cpp.
                                                              {
    // 幂等：同名场已存在则直接返回
    auto it = fields_.find(fieldName);
    if (it != fields_.end()) {
        LOG_WARNING("[FieldManager] Field '" + fieldName +
                    "' already exists. Returning existing instance.");
        return it->second.get();
    }
    // 通过 FieldRegistry 工厂创建
    auto field = FieldRegistry::getInstance().createField(typeName, fieldName);
    if (!field) {
        LOG_ERROR("[FieldManager] Failed to create field '" + fieldName +
                  "' with type '" + typeName + "'.");
        return nullptr;
    }
    Field *ptr = field.get();
    fields_[fieldName] = std::move(field);
    LOG_INFO("[FieldManager] Created field '" + fieldName + "' (type: " +
             typeName + ").");
    return ptr;
}
References GRPD::Field::FieldRegistry::createField(), fields_, GRPD::Field::FieldRegistry::getInstance(), LOG_ERROR, LOG_INFO, and LOG_WARNING.
Referenced by GRPD::Material::ThermalMat::allocateStateVariables().
getField() [1/2]
Field * GRPD::Field::FieldManager::getField (const std::string & name)
获取已注册的物理场基类指针（不存在返回 nullptr）
Definition at line 14 of file FieldManager.cpp.
                                                   {
    auto it = fields_.find(name);
    return (it != fields_.end()) ? it->second.get() : nullptr;
}
References fields_.
getField() [2/2]
const Field * GRPD::Field::FieldManager::getField (const std::string & name) const
Definition at line 19 of file FieldManager.cpp.
                                                               {
    auto it = fields_.find(name);
    return (it != fields_.end()) ? it->second.get() : nullptr;
}
References fields_.
getFieldAs()
template<typename T>
TypedField< T > * GRPD::Field::FieldManager::getFieldAs (const std::string & name)
获取带类型安全的物理场指针（不存在或类型不匹配返回 nullptr）
Template Parameters
T 数据类型
Definition at line 110 of file FieldManager.h.
                                                             {
    auto it = fields_.find(name);
    if (it == fields_.end()) {
        return nullptr;
    }
    return dynamic_cast<TypedField<T> *>(it->second.get());
}
References fields_.
Referenced by GRPD::BC::ConvectionBC::initialize(), GRPD::BC::HeatFluxBC::initialize(), and GRPD::BC::TemperatureBC::initialize().
getFieldCount()
size_t GRPD::Field::FieldManager::getFieldCount () const
获取已注册物理场总数
Definition at line 37 of file FieldManager.cpp.
{ return fields_.size(); }
References fields_.
getFieldNames()
std::vector< std::string > GRPD::Field::FieldManager::getFieldNames () const
获取所有已注册物理场的名称列表（用于调试/VTK 输出枚举）
Definition at line 28 of file FieldManager.cpp.
                                                       {
    std::vector<std::string> names;
    names.reserve(fields_.size());
    for (const auto &pair : fields_) {
        names.push_back(pair.first);
    }
    return names;
}
References fields_.
hasField()
bool GRPD::Field::FieldManager::hasField (const std::string & name) const
检查某个物理场是否已注册
Definition at line 24 of file FieldManager.cpp.
                                                       {
    return fields_.find(name) != fields_.end();
}
References fields_.
operator=() [1/2]
FieldManager & GRPD::Field::FieldManager::operator= (const FieldManager &) [delete]
References FieldManager().
operator=() [2/2]
FieldManager & GRPD::Field::FieldManager::operator= (FieldManager &&) [default]
References FieldManager().
registerField()
template<typename T>
TypedField< T > * GRPD::Field::FieldManager::registerField (const std::string & name, int dim = 1)
注册一个新的物理场 如果同名场已存在，直接返回已有场的指针（幂等操作）
Template Parameters
T 数据类型（默认 double）
Parameters
name 物理场名称（如 "Temperature", "Displacement"）
dim 每个粒子的分量数（标量=1, 矢量=3, 张量=6）
Returns
已注册的 TypedField<T> 指针
Definition at line 96 of file FieldManager.h.
                                                                         {
    // 幂等：如果同名场已存在，直接返回已有指针
    auto it = fields_.find(name);
    if (it != fields_.end()) {
        return dynamic_cast<TypedField<T> *>(it->second.get());
    }
    // 创建新的 TypedField<T> 并注册
    auto field = std::make_unique<TypedField<T>>(name, dim);
    TypedField<T> *ptr = field.get();
    fields_[name] = std::move(field);
    return ptr;
}
References fields_, and GRPD::Field::TypedField< T >::get().
Referenced by GRPD::Field::MechanicalFields::registerFields(), and GRPD::Field::ThermalFields::registerFields().
resizeAll()
void GRPD::Field::FieldManager::resizeAll (size_t numParticles)
对所有已注册的场统一按粒子数分配内存
Parameters
numParticles 粒子总数
Definition at line 70 of file FieldManager.cpp.
                                                {
    for (auto &pair : fields_) {
        pair.second->resize(numParticles);
    }
    LOG_INFO("[FieldManager] Resized all " + std::to_string(fields_.size()) +
             " fields for " + std::to_string(numParticles) + " particles.");
}
References fields_, and LOG_INFO.
Member Data Documentation
fields_
std::map<std::string, std::unique_ptr<Field> > GRPD::Field::FieldManager::fields_ [private]
物理场注册表：场名 -> unique_ptr<Field>
Definition at line 88 of file FieldManager.h.
Referenced by createField(), getField(), getField(), getFieldAs(), getFieldCount(), getFieldNames(), hasField(), registerField(), and resizeAll().
The documentation for this class was generated from the following files:
PDCommon/Field/include/FieldManager.h
PDCommon/Field/src/FieldManager.cpp