GRPD::BC::BCRegistry Class Reference
#include <BCRegistry.h>
Public Member Functions
BCRegistry (const BCRegistry &)=delete
BCRegistry & operator= (const BCRegistry &)=delete
void registerBCType (const std::string &type, BCCreatorFunc creator)
注册一个边界条件类型及其工厂函数
std::unique_ptr< BC > createBC (const std::string &type, const std::string &name)
使用注册的工厂函数创建边界条件实例
Static Public Member Functions
static BCRegistry & getInstance ()
Private Member Functions
BCRegistry ()=default
~BCRegistry ()=default
Private Attributes
std::map< std::string, BCCreatorFunc > registryMap_
Detailed Description
Definition at line 25 of file BCRegistry.h.
Constructor & Destructor Documentation
BCRegistry() [1/2]
GRPD::BC::BCRegistry::BCRegistry (const BCRegistry &) [delete]
References BCRegistry().
Referenced by BCRegistry(), getInstance(), and operator=().
BCRegistry() [2/2]
GRPD::BC::BCRegistry::BCRegistry () [private], [default]
~BCRegistry()
GRPD::BC::BCRegistry::~BCRegistry () [private], [default]
Member Function Documentation
createBC()
std::unique_ptr< BC > GRPD::BC::BCRegistry::createBC (const std::string & type, const std::string & name)
使用注册的工厂函数创建边界条件实例
Parameters
type 已注册的类型名
name 新实例名称
Returns
创建的 BC 智能指针
Definition at line 36 of file BCRegistry.cpp.
                                                                 {
    auto it = registryMap_.find(type);
    if (it == registryMap_.end()) {
        LOG_ERROR("[BCRegistry] Create BC failed: unknown type '" + type + "'!");
        throw std::runtime_error("Unknown BC type: " + type);
    }
    return it->second(name);
}
References LOG_ERROR, and registryMap_.
Referenced by GRPD::IO::GrpdReader::readLoads().
getInstance()
BCRegistry & GRPD::BC::BCRegistry::getInstance () [static]
Definition at line 14 of file BCRegistry.cpp.
                                    {
    static BCRegistry instance;
    return instance;
}
References BCRegistry().
Referenced by GRPD::IO::GrpdReader::readLoads().
operator=()
BCRegistry & GRPD::BC::BCRegistry::operator= (const BCRegistry &) [delete]
References BCRegistry().
registerBCType()
void GRPD::BC::BCRegistry::registerBCType (const std::string & type, BCCreatorFunc creator)
注册一个边界条件类型及其工厂函数
Parameters
type 边界条件类型名（如 "ThermalBC"）
creator 创建该类型实例的工厂函数
Definition at line 22 of file BCRegistry.cpp.
                                                       {
    if (registryMap_.find(type) != registryMap_.end()) {
        LOG_WARNING("[BCRegistry] BC type '" + type +
                    "' already registered, overwriting.");
    } else {
        LOG_INFO("[BCRegistry] BC type '" + type + "' registered.");
    }
    registryMap_[type] = creator;
}
References LOG_INFO, LOG_WARNING, and registryMap_.
Member Data Documentation
registryMap_
std::map<std::string, BCCreatorFunc> GRPD::BC::BCRegistry::registryMap_ [private]
Definition at line 57 of file BCRegistry.h.
Referenced by createBC(), and registerBCType().
The documentation for this class was generated from the following files:
PDCommon/BC/include/BCRegistry.h
PDCommon/BC/src/BCRegistry.cpp