GRPD::Field::Field Class Reference
#include <Field.h>
Public Member Functions
Field (const std::string &name, int dim=1)
构造函数
virtual ~Field ()=default
Field (const Field &)=delete
Field & operator= (const Field &)=delete
Field (Field &&)=default
Field & operator= (Field &&)=default
const std::string & getName () const
获取物理场名称
int getDim () const
获取每个粒子的分量维度（标量=1, 矢量=3, 张量=9）
virtual void resize (size_t numParticles)=0
按粒子总数分配/重新分配内存，初始化为零值
virtual size_t size () const =0
当前已分配的粒子数量
virtual void clearToZero ()=0
将所有数据清零（每个时间步开始时重置变化率等场量）
virtual double * rawPtr ()=0
获取底层连续内存的 double 裸指针（用于 VTK 输出 / OpenMP 并行）
virtual const double * rawPtr () const =0
Protected Attributes
std::string name_
int dim_
Detailed Description
Definition at line 17 of file Field.h.
Constructor & Destructor Documentation
Field() [1/3]
GRPD::Field::Field::Field (const std::string & name, int dim = 1) [explicit]
构造函数
Parameters
name 物理场名称（如 "Temperature", "Displacement"）
dim 每个粒子的分量数（标量=1, 矢量=3, 对称张量=6）
Definition at line 12 of file Field.cpp.
    : name_(name), dim_(dim) {}
References dim_, and name_.
Referenced by Field(), Field(), operator=(), operator=(), and GRPD::Field::TypedField< T >::TypedField().
~Field()
virtual GRPD::Field::Field::~Field () [virtual], [default]
Field() [2/3]
GRPD::Field::Field::Field (const Field &) [delete]
References Field().
Field() [3/3]
GRPD::Field::Field::Field (Field &&) [default]
References Field().
Member Function Documentation
clearToZero()
virtual void GRPD::Field::Field::clearToZero () [pure virtual]
将所有数据清零（每个时间步开始时重置变化率等场量）
Implemented in GRPD::Field::TypedField< T >, and GRPD::Field::TypedField< double >.
getDim()
int GRPD::Field::Field::getDim () const
获取每个粒子的分量维度（标量=1, 矢量=3, 张量=9）
Definition at line 20 of file Field.cpp.
{ return dim_; }
References dim_.
getName()
const std::string & GRPD::Field::Field::getName () const
获取物理场名称
Definition at line 18 of file Field.cpp.
{ return name_; }
References name_.
operator=() [1/2]
Field & GRPD::Field::Field::operator= (const Field &) [delete]
References Field().
operator=() [2/2]
Field & GRPD::Field::Field::operator= (Field &&) [default]
References Field().
rawPtr() [1/2]
virtual const double * GRPD::Field::Field::rawPtr () const [pure virtual]
Implemented in GRPD::Field::TypedField< T >.
rawPtr() [2/2]
virtual double * GRPD::Field::Field::rawPtr () [pure virtual]
获取底层连续内存的 double 裸指针（用于 VTK 输出 / OpenMP 并行）
Implemented in GRPD::Field::TypedField< T >, and GRPD::Field::TypedField< double >.
resize()
virtual void GRPD::Field::Field::resize (size_t numParticles) [pure virtual]
按粒子总数分配/重新分配内存，初始化为零值
Parameters
numParticles 粒子总数
Implemented in GRPD::Field::TypedField< T >, and GRPD::Field::TypedField< double >.
size()
virtual size_t GRPD::Field::Field::size () const [pure virtual]
当前已分配的粒子数量
Implemented in GRPD::Field::TypedField< T >, and GRPD::Field::TypedField< double >.
Member Data Documentation
dim_
int GRPD::Field::Field::dim_ [protected]
Definition at line 62 of file Field.h.
Referenced by GRPD::Field::TypedField< T >::add(), Field(), GRPD::Field::TypedField< T >::get(), getDim(), GRPD::Field::TypedField< T >::resize(), GRPD::Field::TypedField< T >::set(), and GRPD::Field::TypedField< T >::size().
name_
std::string GRPD::Field::Field::name_ [protected]
Definition at line 61 of file Field.h.
Referenced by Field(), and getName().
The documentation for this class was generated from the following files:
PDCommon/Field/include/Field.h
PDCommon/Field/src/Field.cpp